const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const apiServer = fs.readFileSync(path.join(root, 'backend/Api.js'), 'utf8');
const engine = fs.readFileSync(path.join(root, 'backend/engines/AppearanceEngine.js'), 'utf8');
const apiClient = fs.readFileSync(path.join(root, 'frontend/js/api.js'), 'utf8');
const apiMirror = fs.readFileSync(path.join(root, 'frontend/api.js'), 'utf8');
const manager = fs.readFileSync(path.join(root, 'frontend/js/pages/adminAppearance.js'), 'utf8');
const sw = fs.readFileSync(path.join(root, 'frontend/sw.js'), 'utf8');

assert(apiServer.includes('if (action === "adminSetupAppearanceSystem")') && apiServer.includes('apiAdminSetupAppearanceSystem(params)'), 'GET router must expose Appearance setup.');
assert(apiClient.includes('return api("adminSetupAppearanceSystem", { singleStep: "true" });'), 'Appearance setup must bypass upload proxy.');
assert.strictEqual(apiClient, apiMirror, 'Frontend API mirrors must stay synchronized.');
assert(apiClient.includes('"adminSetupAppearanceSystem"') && apiClient.includes('"adminGetAppearanceDashboard"'), 'Appearance startup actions must use long timeout coverage.');
assert(engine.includes('function appearanceSpreadsheet_()'), 'Appearance spreadsheet access retry helper missing.');
assert(engine.includes('const singleStep = appearanceBool_(payload.singleStep, false);'), 'Staged setup mode missing.');
assert(engine.includes('createdSheet: spec.name'), 'Staged setup should report the created sheet.');
assert(engine.includes('const seedComplete = !!appearanceFindById_'), 'Dashboard must not report setup complete until built-in packs/themes are seeded.');
assert(manager.includes('setupAttempt < 8'), 'Appearance Manager must repeat staged setup until ready.');
assert(manager.includes('dashboard.setupComplete !== true'), 'Appearance Manager must verify setup completion.');
assert(sw.includes('awards-app-v327-question-drag-order-v1216-v328-appearance-manager-v1217d-v1217g-iphone-pwa-recovery-v1217h-appearance-images-v1217i-appearance-runtime-v1217k-appearance-studio-v1217l-advanced-layout-v1217m-studio-canvas-v1217n-layout-repair-v1217o-team-canvas-v1217p-image-modes-v1217q-score-style-v1217r-page-question-designer-v1217s-preview-runtime-sync-v1217t-studio-refinement-v1217u-admin-help-v1217v-studio-control-fixes-v1217x-pack-selection-compact-actions-v1217x-pack-media-workflow-v1217y-pack-visibility-v1218a-device-login-v1218a1-auth-tabs-v1218b-home-hub-v1218c-player-hubs-v1218c1-home-identity-v1218c2-hub-media-gradients-v1218c3-live-preview-v1218c4-image-tone-league-cards-v1218c5-subhub-profile-alias-v1218c6-hub-nav-cleanup-v1218d-scoreboard-leaderboard-v1218d1-career-stats-cleanup-v1218e-player-identity-notifications-v1218e1-profile-polish-v1218f-push-notifications-v1218f1-global-mode-persistence-v1218f2-push-registration-v1218f3-registration-verification-v1218f4-notification-sheet-repair-v1218f5-vapid-alignment-v1218f6-pattc-predicts'), 'Service worker cache must be bumped for v1.2.17f.');
console.log('PASS: Appearance setup transport/reliability v1.2.17f tests.');
