'use strict';
const fs = require('fs');
const path = require('path');
const assert = require('assert');
const root = path.join(__dirname, '..');
const read = rel => fs.readFileSync(path.join(root, rel), 'utf8');
const awards = read('frontend/js/pages/adminAwards.js');
const app = read('frontend/js/app.js');
const html = read('frontend/app.html');
const sw = read('frontend/sw.js');
assert(awards.includes('id="awardsInlineWorkspace-${index}"'), 'Awards event editor must expand directly under its event.');
assert(awards.includes('>Configure<') || awards.includes('Configure\n'), 'Compact Configure action missing.');
assert(awards.includes('awardsAdminRenderCompactEventEditor_'), 'Compact event editor is missing.');
assert(awards.includes('Advanced Settings') && awards.includes('Markets / Answers'), 'Event editor must keep advanced settings and markets collapsible.');
assert(awards.includes('Answer Text'), 'Event editor must support player-facing answer text edits.');
assert(awards.includes('Loading…'), 'Configure action must show visible loading feedback.');
assert(app.includes('327-question-drag-order-v1216'), 'Awards mobile workflow asset marker missing from app.js.');
assert(html.includes('327-question-drag-order-v1216'), 'Awards mobile workflow asset marker missing from app.html.');
assert(sw.includes('awards-app-v327-question-drag-order-v1216-v328-appearance-manager-v1217d-v1217g-iphone-pwa-recovery-v1217h-appearance-images-v1217i-appearance-runtime-v1217k-appearance-studio-v1217l-advanced-layout-v1217m-studio-canvas-v1217n-layout-repair-v1217o-team-canvas-v1217p-image-modes-v1217q-score-style-v1217r-page-question-designer-v1217s-preview-runtime-sync-v1217t-studio-refinement-v1217u-admin-help-v1217v-studio-control-fixes-v1217x-pack-selection-compact-actions-v1217x-pack-media-workflow-v1217y-pack-visibility-v1218a-device-login-v1218a1-auth-tabs-v1218b-home-hub-v1218c-player-hubs-v1218c1-home-identity-v1218c2-hub-media-gradients-v1218c3-live-preview-v1218c4-image-tone-league-cards-v1218c5-subhub-profile-alias-v1218c6-hub-nav-cleanup-v1218d-scoreboard-leaderboard-v1218d1-career-stats-cleanup-v1218e-player-identity-notifications-v1218e1-profile-polish-v1218f-push-notifications-v1218f1-global-mode-persistence-v1218f2-push-registration-v1218f3-registration-verification-v1218f4-notification-sheet-repair-v1218f5-vapid-alignment-v1218f6-pattc-predicts'), 'Awards mobile workflow cache marker missing.');
console.log('Awards Manager compact event editor tests passed.');
