'use strict';
const fs = require('fs');
const path = require('path');
const assert = require('assert');
const root = path.join(__dirname, '..');
const read = rel => fs.readFileSync(path.join(root, rel), 'utf8');
const awards = read('frontend/js/pages/adminAwards.js');
const picks = read('frontend/js/pages/picks.js');
const css = read('frontend/css/styles.css');
const app = read('frontend/js/app.js');
const sw = read('frontend/sw.js');

assert(awards.includes('id="awardsSection1"') && awards.includes('id="awardsSection2"') && awards.includes('id="awardsSection3"'), 'Awards main sections must be collapsible details.');
assert(awards.includes('What this section does:'), 'Awards sections need specific workflow help.');
assert(awards.includes('id="awardsSearchCategory"') && awards.includes('Any category'), 'Provider category filter must be a dropdown.');
assert(awards.includes('awardsAdminRefreshCategoryOptions_'), 'Category dropdown must populate from provider results.');
assert(awards.includes('adminAwardsToggleAllEvents_') && awards.includes('awardsToggleAllEventsButton'), 'Check/Clear all must use one toggle button.');
assert(awards.includes('Build All Unbuilt Questions'), 'Final batch action must build only unbuilt questions.');
assert(awards.includes('awardsAdminRenderCompactEventEditor_'), 'Compact inline event editor missing.');
assert(awards.includes('Advanced Settings') && awards.includes('Markets / Answers') && awards.includes('Answer Text'), 'Compact event editor must expose question/advanced/answers workflow.');
assert(awards.includes('adminAwardsMoveBatchRow_') && awards.includes('adminAwardsBatchDrop_'), 'Awards question queue must support up/down and drag/drop ordering.');
assert(awards.includes('awardsAdminSetBuildProgress_') && awards.includes('awardsBuildProgressBar'), 'Batch build needs overall progress feedback.');
assert(awards.includes('Keep this Awards Manager page open while the build is running'), 'Current client-driven build requirement must be explicit.');
assert(picks.includes('Pick saved · Tap to change until lock'), 'Player pick card must clearly expose unlimited pick changes.');
assert(css.includes('.awards-answer-card') && css.includes('@media (max-width: 720px)') && css.includes('.awards-market-modal'), 'Awards market/answer UI must have mobile card/modal styling.');
assert(app.includes('327-question-drag-order-v1216'), 'v324 mobile workflow asset marker missing.');
assert(sw.includes('awards-app-v327-question-drag-order-v1216-v328-appearance-manager-v1217d-v1217g-iphone-pwa-recovery-v1217h-appearance-images-v1217i-appearance-runtime-v1217k-appearance-studio-v1217l-advanced-layout-v1217m-studio-canvas-v1217n-layout-repair-v1217o-team-canvas-v1217p-image-modes-v1217q-score-style-v1217r-page-question-designer-v1217s-preview-runtime-sync-v1217t-studio-refinement-v1217u-admin-help-v1217v-studio-control-fixes-v1217x-pack-selection-compact-actions-v1217x-pack-media-workflow-v1217y-pack-visibility-v1218a-device-login-v1218a1-auth-tabs-v1218b-home-hub-v1218c-player-hubs-v1218c1-home-identity-v1218c2-hub-media-gradients-v1218c3-live-preview-v1218c4-image-tone-league-cards-v1218c5-subhub-profile-alias-v1218c6-hub-nav-cleanup-v1218d-scoreboard-leaderboard-v1218d1-career-stats-cleanup-v1218e-player-identity-notifications-v1218e1-profile-polish-v1218f-push-notifications-v1218f1-global-mode-persistence-v1218f2-push-registration-v1218f3-registration-verification-v1218f4-notification-sheet-repair-v1218f5-vapid-alignment-v1218f6-pattc-predicts'), 'v324 service worker cache marker missing.');
console.log('PASS: Awards Manager mobile workflow tests');
