const assert=require('assert');
const path=require('path');
const fs=require('fs');
const root=path.resolve(__dirname,'..');
const componentPath=path.join(root,'frontend/js/pages/castleSpecialEncounterCardsR1.js');
const galleryPath=path.join(root,'frontend/review/castle-special-card-pack-r1.html');
assert(fs.existsSync(componentPath),'component pack missing');
assert(fs.existsSync(galleryPath),'isolated gallery missing');
const source=fs.readFileSync(componentPath,'utf8');
const gallery=fs.readFileSync(galleryPath,'utf8');
['randomizer','candidate','revealedTraitor','masked','fate','murderer','envelopes','ally','history','sealed','finale'].forEach(name=>assert(source.includes(name+':'+name)||source.includes('function '+name+'('),`missing component ${name}`));
assert(source.includes('border-radius:5px'),'common cards must use small radius');
assert(source.includes('border-radius:4px'),'controls/details must use small radius');
assert(source.includes('min-height:44px'),'buttons must retain mobile-safe tap area');
assert(source.includes('rgba('),'translucent panels expected');
assert(source.includes('csec-room--traitor'),'traitor-aware room treatment missing');
assert(source.includes('csec-room--masked'),'masked room treatment missing');
assert(source.includes('csec-room--finale'),'finale room treatment missing');
assert(source.includes('REVEALED TRAITOR'),'revealed traitor presentation missing');
assert(source.includes('HOST REWARD'),'host envelopes missing');
assert(source.includes('Castle Five Ally'),'ally treatment missing');
assert(source.includes('Decision<span>Sealed'),'decision sealed two-line treatment missing');
assert(!source.includes('fetch('),'component pack must not make backend calls');
assert(!source.includes('castleCall_'),'component pack must not call Castle backend');
assert(!source.includes('google.script.run'),'component pack must not call Apps Script');
assert(!gallery.includes('fetch('),'gallery must not call backend');
assert(!gallery.includes('castleCall_'),'gallery must not call Castle backend');
assert(gallery.includes('width:min(100%,430px)'),'gallery must cap review width at 430px');
assert(source.includes('@media(min-width:390px)'),'component pack must include 390px refinement');
assert(gallery.includes('No live Castle state, backend requests, scoring, or sealed-result logic.'),'gallery must state isolation');
console.log('Castle special encounter card pack R1 tests: PASS');
