const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const setup = fs.readFileSync(path.join(root, 'frontend/js/pages/adminGameSetup.js'), 'utf8');
const api = fs.readFileSync(path.join(root, 'frontend/js/api.js'), 'utf8');
const backendApi = fs.readFileSync(path.join(root, 'backend/Api.js'), 'utf8');
const categories = fs.readFileSync(path.join(root, 'backend/admin/AdminCategories.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'frontend/css/styles.css'), 'utf8');
const sw = fs.readFileSync(path.join(root, 'frontend/sw.js'), 'utf8');

assert(setup.includes('The saved question mode is preserved.'));
assert(setup.includes('adminSetupDefaultScoreMode_(game)'));
assert(setup.includes('Delete Question'));
assert(setup.includes('adminSetupDeleteCategory'));
assert(setup.includes('CHANGES MADE — SAVE NOW'));
assert(setup.includes('CHANGES MADE — SAVE ALL NOW'));
assert(setup.includes('ALL CHANGES SAVED ✓'));
assert(setup.includes('apiAdminBulkUpdateGameSetup'));
assert(setup.includes('data-question-editor'));
assert(setup.includes('data-answer-editor'));
assert(api.includes('async function apiAdminBulkUpdateGameSetup'));
assert(api.includes('compatibilityFallback: true'));
assert(api.includes('Unknown action:\\s*adminBulkUpdateGameSetup'));
assert(setup.includes('Question ID (permanent):'));
assert(setup.includes('Answer ID (permanent):'));
assert(setup.includes('adminSetupSyncQuestionDisplay_'));
assert(setup.includes('adminSetupSyncAnswerDisplay_'));
assert(api.includes('async function apiAdminDeleteCategory'));
assert(backendApi.includes('"adminBulkUpdateGameSetup"'));
assert(backendApi.includes('"adminDeleteCategory"'));
assert(categories.includes('function adminCatResolveScoreModeForGame_'));
assert(categories.includes('function adminBulkUpdateGameSetup'));
assert(categories.includes('function adminDeleteCategory'));
assert(categories.includes('cannot be permanently deleted'));
assert(css.includes('.admin-save-state-button.is-dirty'));
assert(css.includes('.admin-save-state-button.is-saved'));
assert(sw.includes('awards-app-v327-question-drag-order-v1216-v328-appearance-manager-v1217d-v1217g-iphone-pwa-recovery-v1217h-appearance-images-v1217i-appearance-runtime-v1217k-appearance-studio-v1217l-advanced-layout-v1217m-studio-canvas-v1217n-layout-repair-v1217o-team-canvas-v1217p-image-modes-v1217q-score-style-v1217r-page-question-designer-v1217s-preview-runtime-sync-v1217t-studio-refinement-v1217u-admin-help-v1217v-studio-control-fixes-v1217x-pack-selection-compact-actions-v1217x-pack-media-workflow-v1217y-pack-visibility-v1218a-device-login-v1218a1-auth-tabs-v1218b-home-hub-v1218c-player-hubs-v1218c1-home-identity-v1218c2-hub-media-gradients-v1218c3-live-preview-v1218c4-image-tone-league-cards-v1218c5-subhub-profile-alias-v1218c6-hub-nav-cleanup-v1218d-scoreboard-leaderboard-v1218d1-career-stats-cleanup-v1218e-player-identity-notifications-v1218e1-profile-polish-v1218f-push-notifications-v1218f1-global-mode-persistence-v1218f2-push-registration-v1218f3-registration-verification-v1218f4-notification-sheet-repair-v1218f5-vapid-alignment-v1218f6-pattc-predicts'));

console.log('game-setup-editor-workflow-tests: PASS');
