const fs=require("fs"),assert=require("assert"),vm=require("vm");
const engine=fs.readFileSync("backend/engines/NflPlayoffRaceEngine.js","utf8");
const front=fs.readFileSync("frontend/js/pages/rankingSportsR1.js","utf8");
const css=fs.readFileSync("frontend/css/nfl-sports-pack-r1.css","utf8");
const rank=fs.readFileSync("backend/engines/RankingGameEngine.js","utf8");
const ctx={console,Math,Date,JSON,Number,String,Array,Object,RegExp,Set};
ctx.rankingBallotValid_=()=>true;ctx.rankingFinalOrderComplete_=()=>true;
vm.createContext(ctx);vm.runInContext(engine,ctx);
const run=s=>vm.runInContext(s,ctx);
assert.strictEqual(run("nflPlayoffRaceCheckpointMultiplier_(4)"),.95);
assert.strictEqual(run("nflPlayoffRaceCheckpointMultiplier_(8)"),.85);
assert.strictEqual(run("nflPlayoffRaceCheckpointMultiplier_(12)"),.65);
assert.strictEqual(run("nflPlayoffRaceCheckpointMultiplier_(15)"),.40);
assert.strictEqual(run("nflPlayoffRaceLiveGame_({active:false,status:'Draft'})"),false);
assert.strictEqual(run("nflPlayoffRaceLiveGame_({active:true,status:'Live'})"),true);
assert(engine.includes('effectiveWeek=meta.setupMode?0:meta.timing.currentWindow.week'));
assert(engine.includes('meta.setupMode\n    ?Object.fromEntries'));
assert.strictEqual(run("nflPlayoffRacePositionPoints_(1,1)"),20);
assert.strictEqual(run("nflPlayoffRacePositionPoints_(1,2)"),15);
assert.strictEqual(run("nflPlayoffRacePositionPoints_(1,3)"),10);
assert.strictEqual(run("nflPlayoffRacePositionPoints_(1,4)"),6);
assert.strictEqual(run("nflPlayoffRacePositionPoints_(1,5)"),3);
assert.strictEqual(run("nflPlayoffRacePositionPoints_(1,6)"),0);
ctx.category={id:"afc-playoff-seeds",points:160,nominees:Array.from({length:16},(_,i)=>({id:String.fromCharCode(65+i)}))};
ctx.ballot=ctx.category.nominees.map((x,i)=>({nomineeId:x.id,rank:i+1}));
ctx.final=Object.fromEntries(ctx.ballot.map(x=>[x.nomineeId.toLowerCase(),x.rank]));
ctx.snap={multiplier:1,rankingsJSON:JSON.stringify(ctx.ballot),teamMultipliersJSON:JSON.stringify(Object.fromEntries(ctx.ballot.map(x=>[x.nomineeId.toLowerCase(),1])))};
ctx.hist=[{forecastType:"original",submittedAt:"2026-08-01T00:00:00Z",rankingsJSON:JSON.stringify(ctx.ballot)}];
const weighted=run("nflPlayoffRaceWeightedScore_(category,ballot,final,snap,hist)");
assert.strictEqual(weighted.finalForecastPoints,320);
assert.strictEqual(weighted.playoffFieldBonus,26);
assert.strictEqual(weighted.originalHoldBonus,80);
assert.strictEqual(weighted.earnedPoints,426);
ctx.standings=[{nomineeId:"A",rank:1},{nomineeId:"B",rank:3},{nomineeId:"C",rank:8}];
ctx.picks=[{nomineeId:"A",rank:1},{nomineeId:"B",rank:2},{nomineeId:"C",rank:3}];
assert.deepStrictEqual(JSON.parse(JSON.stringify(run("nflPlayoffRaceCheckpointScore_(picks,standings)"))),{exactSeedPoints:3,nearSeedPoints:1,playoffFieldPoints:2,total:6});
ctx.changed=[ctx.hist[0],{forecastType:"update",submittedAt:"2026-09-30T00:00:00Z",rankingsJSON:JSON.stringify(ctx.ballot.map(x=>x.nomineeId==="A"?{nomineeId:"A",rank:2}:x))}];
assert.strictEqual(run("nflPlayoffRaceOriginalHoldBonus_(changed,final).eligibleTeams.includes('a')"),false);
assert.strictEqual(run("nflPlayoffRaceCheckpointKey_('g','User','afc',4)===nflPlayoffRaceCheckpointKey_('g','user','AFC',4)"),true);
ctx.calls=0;ctx.nflPlayoffRaceFetchWeek_=function(){ctx.calls++;return [{Status:"Final"}];};ctx.req=run("nflPlayoffRaceRequestContext_('nfl-playoff-race-2026')");
run("nflPlayoffRaceFetchWeekContext_(req,4);nflPlayoffRaceFetchWeekContext_(req,4)");
assert.strictEqual(ctx.calls,1);assert.strictEqual(ctx.req.weekScheduleCacheHits,1);
assert(front.includes("Checkpoint Points")&&front.includes("Original Hold Bonuses"));
assert(front.includes("<strong>20</strong><span>EXACT</span>")&&front.includes("20·15·10·6·3"));
assert(front.includes('conference+" #"+liveRow.currentRank+compactMovement(liveRow)+" | "+(div||liveRow.division||"")+" #"+divRank+" | ("+(liveRow.record||"0-0-0")+")"'));
assert(front.includes('base+" pts"+(bonus>0?" (+"+bonus+" bonus)":"")'));
assert(!front.includes(" playoff</b>"));
assert(front.includes("nfl-race-season-strip")&&front.includes("nfl-race-stage-strip"));
assert(front.includes("controls(category,team,index,ordered.length,locked,teamPctLabel)"));
assert(css.includes(".nfl-ranking-control-group")&&css.includes("background:transparent!important"));
assert(css.includes("min-height:38px!important")&&css.includes("grid-template-columns:18px 28px 18px 17px!important"));
assert(css.includes(".nfl-ranking-row-points")&&css.includes("font-size:12px!important"));
assert(engine.includes("NflForecastCheckpointScores"));
assert(rank.includes("nflCheckpointByUser"));
assert(!front.includes("Week 4:</strong> 85%"));
console.log("PATTC NFL Playoff Race Season Game R1 focused regression: PASS");
