const fs=require("fs"),assert=require("assert"),vm=require("vm");
const be=fs.readFileSync("backend/engines/NflPlayoffRaceEngine.js","utf8");
const ranking=fs.readFileSync("backend/engines/RankingGameEngine.js","utf8");
const api=fs.readFileSync("backend/Api.js","utf8");
const sec=fs.readFileSync("backend/core/ApiSecurity.js","utf8");
const ctx={console,Math,Date,JSON,Number,String,Array,Object,RegExp};
vm.createContext(ctx);vm.runInContext(be,ctx);
assert.strictEqual(vm.runInContext("nflPlayoffRaceLateEntryMultiplier_(1,true)",ctx),0.95);
assert.strictEqual(vm.runInContext("nflPlayoffRaceLateEntryMultiplier_(4,true)",ctx),0.80);
assert.strictEqual(vm.runInContext("nflPlayoffRaceLateEntryMultiplier_(10,true)",ctx),0.50);
assert.strictEqual(vm.runInContext("nflPlayoffRaceLateEntryMultiplier_(1,false)",ctx),1);
assert.strictEqual(vm.runInContext("nflPlayoffRaceCheckpointMultiplier_(4)",ctx),0.85);
assert.strictEqual(vm.runInContext("nflPlayoffRaceCheckpointMultiplier_(8)",ctx),0.70);
assert.strictEqual(vm.runInContext("nflPlayoffRaceCheckpointMultiplier_(12)",ctx),0.55);
assert.strictEqual(vm.runInContext("nflPlayoffRaceCheckpointMultiplier_(15)",ctx),0.40);
assert(be.includes('"NflForecastSnapshots"'));
assert(be.includes("legacy-ranking-migration"));
assert(be.includes("saveRankingBallot_"));
assert(be.includes("NFL_PLAYOFF_RACE_FINAL_ENTRY_WEEK_ = 10"));
assert(be.includes("nflPlayoffRaceMultiplierMapForGame_"));
assert(ranking.includes("nflPlayoffRaceMultiplierMapForGame_"));
assert(ranking.includes("baseEarnedPoints"));
assert(api.includes('action === "getNflPlayoffRaceState"'));
assert(api.includes('action === "saveNflPlayoffRaceRanking"'));
assert(sec.includes("saveNflPlayoffRaceRanking: true"));
console.log("PATTC NFL Playoff Race Rules R1 tests: PASS");
