const fs=require("fs"),assert=require("assert"),read=p=>fs.readFileSync(p,"utf8");
const engine=read("backend/engines/NflPlayoffRaceEngine.js"),rankEngine=read("backend/engines/RankingGameEngine.js");
const api=read("backend/Api.js"),route=read("functions/api/app.js"),admin=read("frontend/js/pages/adminGamesRc24e.js");
const rank=read("frontend/js/pages/rankingSportsR1.js"),css=read("frontend/css/nfl-sports-pack-r1.css");
const app=read("frontend/js/app.js"),mirror=read("frontend/app.js"),html=read("frontend/app.html");
assert(engine.includes('NFL_PLAYOFF_RACE_TEAM_BONUS_ = 3'));
assert(engine.includes('NFL_PLAYOFF_RACE_PERFECT_FIELD_BONUS_ = 5'));
assert(engine.includes('NFL_PLAYOFF_RACE_SETTINGS_SHEET_ = "NflPlayoffRaceSettings"'));
assert(engine.includes("apiAdminSaveNflPlayoffRaceSettings_"));
assert(engine.includes('settings.updateWindowMode==="open"'));
assert(engine.includes("nflPlayoffRaceLatestFinalWeek_"));
assert(engine.includes("nflPlayoffRaceLiveCategory_"));
assert(engine.includes("correctPlayoffTeams"));
assert(engine.includes("perfectFieldBonus"));
assert(rankEngine.includes("nflPlayoffRaceBonusForBallot_"));
assert(api.includes('action === "adminGetNflPlayoffRaceSettings"'));
assert(api.includes('action === "adminSaveNflPlayoffRaceSettings"'));
assert(route.includes('"adminGetNflPlayoffRaceSettings"'));
assert(route.includes('"adminSaveNflPlayoffRaceSettings"'));
assert(admin.includes("NFL Playoff Race Timing"));
assert(admin.includes("Open Now"));
assert(rank.includes("IF THE SEASON ENDED TODAY"));
assert(rank.includes("ADJUSTMENT SCHEDULE"));
assert(rank.includes("playoff"));
assert(css.includes("PATTC NFL PLAYOFF RACE R2"));
assert(app.includes('v1219-nfl-playoff-race-r2'));
assert.strictEqual(app,mirror);
assert(html.includes("playoff=v1219-nfl-playoff-race-r2"));
console.log("PATTC NFL Playoff Race R2 finalization tests: PASS");