/* PATTC NFL Cup + Futures R1 targeted source-integrity regressions. */
const fs=require('fs'), assert=require('assert'), vm=require('vm');
const read=p=>fs.readFileSync(p,'utf8');
const engine=read('backend/engines/NflCupFuturesEngine.js');
const bet=read('backend/engines/BettingEngine.js');
const scoring=read('backend/engines/ScoringEngine.js');
const hybrid=read('backend/engines/HybridGameEngine.js');
const api=read('backend/Api.js');
const route=read('functions/api/app.js');
const cup=read('frontend/js/pages/nflCupR1.js');
const hub=read('frontend/js/pages/seasonHub.js');
const admin=read('frontend/js/pages/adminGamesRc24e.js');
const wager=read('frontend/js/pages/betting.js');
const html=read('frontend/app.html');
assert(engine.includes('function apiAdminPrepareNflCupFuturesR1_'));
assert(engine.includes("requireAdmin_(payload)"));
assert(engine.includes("ids.confidence")&&engine.includes("ids.survivor")&&engine.includes("ids.fantasy"));
assert(engine.includes("wagerEditMode:'final_once_selected'")&&engine.includes("allowBetRemoval:false"));
assert(engine.includes('function nflCupFuturesSettledForCup_'));
assert(engine.includes('function nflCupTeamFantasyLeaderboard_'));
assert(bet.includes('NFL_CUP_FUTURES_R1_FIXED_ALLOCATION'));
assert(bet.includes('config.startingBankroll - Number(currentSummary.totalStaked || 0)'));
assert(scoring.includes('NFL_CUP_FUTURES_R1_LEADERBOARD_ADAPTER'));
assert(hybrid.includes('NFL_CUP_FUTURES_R1_CUP_ADAPTER'));
assert(api.includes('adminPrepareNflCupFuturesR1'));
assert(route.includes('adminPrepareNflCupFuturesR1'));
assert(cup.includes('nfl-cup-r2-hero')&&cup.includes('miniGameContributions'));
assert(hub.includes('__PATTC_NFL_CUP_CONTEXT__'));
assert(admin.includes('nflCupFuturesAdminBuild_'));
assert(wager.includes('nfl-futures-r1-hero')&&wager.includes('const isNflFuturesR1'));
assert(html.includes('nfl-cup-futures-r1.css'));
assert(read('frontend/app.js')===read('frontend/js/app.js'));
// Pure rules under mocked dependencies. Never touches live Sheets.
const ctx={NFL_SEASON_PACK_TEAMS_:[],console:console};
['AFC','NFC'].forEach(conference=>['East','North','South','West'].forEach(division=>[1,2,3,4].forEach(n=>ctx.NFL_SEASON_PACK_TEAMS_.push({abbr:conference.slice(0,1)+division.slice(0,1)+n,name:conference+' '+division+' '+n,conference,division}))));
vm.createContext(ctx);vm.runInContext(engine,ctx);
const markets=ctx.nflCupFuturesMarkets_();
assert.strictEqual(markets.length,13);
assert.strictEqual(markets.filter(m=>m.teams.length===4).length,8);
assert.strictEqual(markets[0].teams.length,32);
assert.strictEqual(markets[1].teams.length,16);
assert.throws(()=>ctx.nflCupFuturesYear_(2025));
ctx.getCategories=()=>[{id:'super-bowl-champion'}];ctx.getCategorySettings=()=>({'super-bowl-champion':{winnerNomineeId:''}});
assert.strictEqual(ctx.nflCupFuturesSettledForCup_('nfl-futures-2026'),false);
ctx.getCategorySettings=()=>({'super-bowl-champion':{winnerNomineeId:'BAL'}});
assert.strictEqual(ctx.nflCupFuturesSettledForCup_('nfl-futures-2026'),true);
assert.strictEqual(ctx.nflCupFuturesSettledForCup_('nfl-confidence-2026'),true);
console.log('PATTC NFL Cup + Futures R1 tests: PASS');
