const fs=require('fs'),vm=require('vm'),assert=require('assert');
const engine=fs.readFileSync('backend/engines/NflPlayoffRaceEngine.js','utf8');
const ranking=fs.readFileSync('backend/engines/RankingGameEngine.js','utf8');
const api=fs.readFileSync('backend/Api.js','utf8');
const security=fs.readFileSync('backend/core/ApiSecurity.js','utf8');
const proxy=fs.readFileSync('functions/api/app.js','utf8');
const frontend=fs.readFileSync('frontend/js/pages/rankingSportsR1.js','utf8');
const browserAPI=fs.readFileSync('frontend/api.js','utf8');
assert.strictEqual(browserAPI,fs.readFileSync('frontend/js/api.js','utf8'),'API mirror');
const ctx={Math,JSON,Date,Number,String,Array,Object,RegExp,console};
vm.createContext(ctx); vm.runInContext(engine,ctx);
function run(expr){return vm.runInContext(expr,ctx)}
assert.strictEqual(run('nflPlayoffRaceInitialMultiplier_("nfl-playoff-race-2026",3,true)'),1);
assert.strictEqual(run('nflPlayoffRaceInitialMultiplier_("nfl-playoff-race-2026",4,true)'),.95);
assert.strictEqual(run('nflPlayoffRaceInitialMultiplier_("nfl-playoff-race-2026",10,true)'),.65);
assert.strictEqual(run('nflPlayoffRaceCheckpointMultiplier_(4)'),.85);
ctx.oldSnap={multiplier:1,rankingsJSON:JSON.stringify([{nomineeId:'BAL',rank:1},{nomineeId:'BUF',rank:2},{nomineeId:'KC',rank:3}]),teamMultipliersJSON:'{"bal":1,"buf":1,"kc":1}'};
ctx.next=[{nomineeId:'BAL',rank:2},{nomineeId:'BUF',rank:1},{nomineeId:'KC',rank:3}];
let values=JSON.parse(JSON.stringify(run('nflPlayoffRaceAdjustedTeamMultipliers_(oldSnap,next,.85)')));
assert.deepStrictEqual(values,{bal:.85,buf:.85,kc:1},'Only displaced teams lose multiplier');
ctx.changedSnap={multiplier:.85,rankingsJSON:JSON.stringify(ctx.next),teamMultipliersJSON:JSON.stringify(values)};
let noChanges=JSON.parse(JSON.stringify(run('nflPlayoffRaceAdjustedTeamMultipliers_(changedSnap,next,.70)')));
assert.deepStrictEqual(noChanges,values,'Unchanged teams do not lose multiplier at a later checkpoint');
let reverted=JSON.parse(JSON.stringify(run('nflPlayoffRaceAdjustedTeamMultipliers_(changedSnap,JSON.parse(oldSnap.rankingsJSON),.70)')));
assert.deepStrictEqual(reverted,{bal:.70,buf:.70,kc:1},'Reverting position never restores 100%');
assert.deepStrictEqual(JSON.parse(JSON.stringify(run('nflPlayoffRaceSnapshotTeamMultipliers_(changedSnap)'))),values,'Previous 100% remains even with 85% category metadata');
ctx.legacy={multiplier:.7,rankingsJSON:ctx.oldSnap.rankingsJSON};
assert.deepStrictEqual(JSON.parse(JSON.stringify(run('nflPlayoffRaceSnapshotTeamMultipliers_(legacy)'))),{bal:.7,buf:.7,kc:.7},'Legacy category-wide snapshots migrate on read');
ctx.rankingBallotValid_=(cat,ballot)=>ballot.length===cat.nominees.length;
ctx.rankingFinalOrderComplete_=(cat,final)=>Object.keys(final).length===cat.nominees.length;
ctx.category={id:'afc-seed-order',points:30,nominees:[{id:'BAL'},{id:'BUF'},{id:'KC'}]};
ctx.final={bal:2,buf:1,kc:3};
let score=JSON.parse(JSON.stringify(run('nflPlayoffRaceWeightedScore_(category,next,final,changedSnap)')));
assert.strictEqual(score.earnedPoints,27,'exact scores: 8.5 + 8.5 + 10');
assert.strictEqual(score.finalPointsAvailable,27,'max position points honor team rates');
assert.strictEqual(score.remainingPoints,0);
ctx.final={};score=JSON.parse(JSON.stringify(run('nflPlayoffRaceWeightedScore_(category,next,final,changedSnap)')));
assert.strictEqual(score.remainingPoints,27,'remaining points use team rates');
assert.strictEqual(score.earnedPoints,0);
assert(frontend.includes('SAVE PICKS (DRAFT)')&&frontend.includes('FINALIZE PICKS'));
assert(frontend.includes('Draft restored'));
assert(frontend.includes('TEAM-SPECIFIC'),'Mixed per-team values are not advertised as a single forecast percentage');
assert(api.includes('action === "saveNflPlayoffRaceDraft"')&&api.includes('action === "finalizeNflPlayoffRaceForecast"'));
assert(security.includes('saveNflPlayoffRaceDraft: true')&&security.includes('finalizeNflPlayoffRaceForecast: true'));
assert(proxy.includes('"saveNflPlayoffRaceDraft"')&&proxy.includes('"finalizeNflPlayoffRaceForecast"'));
assert(proxy.includes('!productionRequest'));
assert(proxy.includes('\"saveNflPlayoffRaceDraft\"') && proxy.includes('\"finalizeNflPlayoffRaceForecast\"'));
assert(proxy.includes('action === \"saveRanking\"'),'Generic ranking path blocked in Playoff Race preview');
assert(engine.includes('if(payload.confirmed!==true)'));
console.log('PATTC Playoff Race R3 per-team multipliers, legacy fallback, Week 3, Draft/Finalize contracts: PASS');
// Full 16-team playoff field: team-specific bonuses and the lowest of top-seven
// rates for the perfect-field bonus, without reducing unchanged predictions.
const fullTeams=['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P'];
ctx.category={id:'afc-playoff-seeds',points:160,nominees:fullTeams.map(id=>({id}))};
ctx.fullBallot=fullTeams.map((id,index)=>({nomineeId:id,rank:index+1}));
ctx.final=Object.fromEntries(fullTeams.map((id,i)=>[id.toLowerCase(),i+1]));
ctx.fullSnap={multiplier:.85,rankingsJSON:JSON.stringify(ctx.fullBallot),teamMultipliersJSON:JSON.stringify(Object.fromEntries(fullTeams.map(id=>[id.toLowerCase(),id==='A'?.85:1])))};
score=JSON.parse(JSON.stringify(run('nflPlayoffRaceWeightedScore_(category,fullBallot,final,fullSnap)')));
assert.strictEqual(score.earnedPoints,183.3,'One reduced team: 158.5 positional + 20.55 team bonus + 4.25 perfect bonus');
assert.strictEqual(score.finalPointsAvailable,183.3);
assert.strictEqual(score.correctPlayoffTeams,7);
ctx.nobodySnap={multiplier:1,rankingsJSON:JSON.stringify(ctx.fullBallot)};
assert.strictEqual(run('nflPlayoffRaceWeightedScore_(category,fullBallot,final,nobodySnap).earnedPoints'),186,'Original full-value 32-team max remains 186 per conference');
assert.strictEqual(run('nflPlayoffRaceStaticLockedR3_({lockAllPicks:true},{locked:false})'),true,'Global lock honored');
assert.strictEqual(run('nflPlayoffRaceStaticLockedR3_({},{locked:true})'),true,'Manual category lock honored');
assert.strictEqual(run('nflPlayoffRaceStaticLockedR3_({},{locked:false,lockDateTime:"2026-09-01"})'),false,'Stale preseason date defers to Playoff Race timing');
assert(ranking.includes('payload.playoffRaceTimingAuthorized !== true'),'Generic saveRanking must not bypass Finalize');
assert(engine.includes('if(!meta.canUpdate)'),'Update window gate is enforced');
assert(engine.includes('if(!meta.canEnter)'),'Original entry gate is enforced');
console.log('PATTC Playoff Race R3 full-field bonuses and lock boundaries: PASS');
