const fs=require("fs"),assert=require("assert"),read=p=>fs.readFileSync(p,"utf8");
const engine=read("backend/engines/NflPlayoffRaceEngine.js");
const rank=read("frontend/js/pages/rankingSportsR1.js");
const nflCss=read("frontend/css/nfl-sports-pack-r1.css");
const confCss=read("frontend/css/confidence-r2.css");
const html=read("frontend/app.html"),app=read("frontend/js/app.js"),mirror=read("frontend/app.js");
assert(engine.includes('Object.assign({},base,{seasonType:2})'));
assert(engine.includes('const attempts=['));
const controls=rank.slice(rank.indexOf("function controls("),rank.indexOf("function divisionWarning("));
assert(controls.indexOf('aria-label="Move up"') < controls.indexOf("nfl-ranking-position-select"));
assert(controls.indexOf("nfl-ranking-position-select") < controls.indexOf('aria-label="Move down"'));
assert(controls.indexOf('aria-label="Move down"') < controls.indexOf("nfl-ranking-drag"));
assert(!controls.includes('draggable="true"'));
assert(controls.includes("onlostpointercapture"));
assert(nflCss.includes("PATTC NFL LAUNCH FINISH R2.1"));
assert(nflCss.includes("grid-template-columns:24px 36px 24px 24px"));
assert(confCss.includes("PATTC CONFIDENCE LAUNCH FINISH R2.1"));
assert(confCss.includes("grid-template-columns:minmax(0,1fr) minmax(0,1fr) 94px"));
assert(confCss.includes("width:52px!important"));
assert(confCss.includes("grid-template-columns:16px minmax(52px,1fr) 16px"));
assert(html.includes("confidence=v1219-confidence-launch-r2-1"));
assert(html.includes("playoff=v1219-nfl-playoff-race-r2-1"));
assert(app.includes('v1219-nfl-playoff-race-r2-1'));
assert.strictEqual(app,mirror);
console.log("PATTC NFL launch finish R2.1 tests: PASS");