'use strict';
const assert = require('assert'), fs = require('fs'), vm = require('vm');
const R3 = require('../frontend/js/ownerVisualStudioR3.js');
const config = {environment:'isolated-test',apiUrl:'https://script.google.com/macros/s/synthetic/exec',scriptId:'synthetic-script',spreadsheetId:'synthetic-sheet'};
const allow = R3.developmentWritePolicy(config, config.apiUrl, config, config);
assert(allow.allowed);
for (const [cfg,url,bridge,identity] of [[null,config.apiUrl], [config,'unknown'],[config,config.apiUrl], [config,config.apiUrl,config,{...config,spreadsheetId:'other'}], [config,config.apiUrl,{...config,apiUrl:'production'},config]]) assert(!R3.developmentWritePolicy(cfg,url,bridge,identity).allowed);
const source = fs.readFileSync('frontend/js/ownerVisualStudioR3.js','utf8');
const production = source.match(/const PRODUCTION_BACKEND = '([^']+)'/)[1];
assert(!R3.developmentWritePolicy({...config,apiUrl:production},production,config,config).allowed);
async function main() {
 let writes=0, allowed=false;
 const adapter={readFresh:async()=>({success:true,overrides:[]}),write:async()=>{writes++;return {success:true};}};
 const c=R3.createController(adapter,{assertWritable(){if(!allowed)throw Error('read-only');},setTimeout(){return 1;},clearTimeout(){}});
 await c.open({gameId:'synthetic',pageKey:'picks'});
 assert.throws(()=>c.edit(m=>{m.hidden.x=true;}),/read-only/);
 assert.throws(()=>c.restoreSelected('x'),/read-only/);
 for(const operation of [()=>c.flush(),()=>c.publish(),()=>c.revert(),()=>c.restore('picks::v')]) await assert.rejects(operation,/read-only/);
 assert(!c.snapshot().dirty); assert.equal(writes,0); await c.close();
 const realAdapter=R3.serverAdapter({PATTC_STUDIO_R3_WRITE_POLICY:{allowed:true,label:'isolated-test'},apiAdminSaveAppearanceOverride(){writes++;}});
 assert.throws(()=>realAdapter.write({},R3.TYPES.draft,'picks',{}),/blocked/); assert.equal(writes,0);
 const ctx={console}; vm.createContext(ctx);
 vm.runInContext(fs.readFileSync('backend/engines/AppearanceEngine.js','utf8'),ctx);
 vm.runInContext(fs.readFileSync('backend/core/ApiSecurity.js','utf8'),ctx);
 const published={version:1,pageKey:'picks',meta:{ownerEmail:'private'},items:{x:{style:{padding:12},privateNote:'secret'}},responsive:{mobile:{items:{x:{style:{padding:8}}}}}};
 const bundle={success:true,gameId:'synthetic',assignment:{GameId:'synthetic',PrivateSettings:'secret'},theme:{colors:{primary:'red'},privateSettings:'secret'},imagePackItems:[{EntityId:'x',ImageUrl:'synthetic.png',SourceUrl:'private'}],overrides:[{EntityType:'visual-studio-draft',ThemeOverrideJSON:'secret'},{EntityType:'visual-studio-version',ThemeOverrideJSON:'secret'},{EntityType:'visual-studio-published',EntityId:'picks',ThemeOverrideJSON:JSON.stringify(published),AdminNotes:'secret'}]};
 const clean=ctx.appearancePublicRuntimeBundle_(bundle);
 assert.equal(clean.overrides.length,1); assert(!JSON.stringify(clean).includes('secret')); assert(!JSON.stringify(clean).includes('private'));
 assert.equal(JSON.parse(clean.overrides[0].ThemeOverrideJSON).items.x.style.padding,12);
 assert.equal(JSON.parse(clean.overrides[0].ThemeOverrideJSON).responsive.mobile.items.x.style.padding,8);
 ctx.appearanceGetRuntimeBundle=()=>bundle;
 assert.equal(ctx.apiGetGameAppearance({gameId:'synthetic'}).overrides.length,1,'Public route sanitizes cached bundles too');
 assert(ctx.apiSecurityAuthorizeRequest_('getGameAppearance',{}).public);
 for(const action of ['adminGetAppearanceDashboard','adminSaveAppearanceOverride']) assert.throws(()=>ctx.apiSecurityAuthorizeRequest_(action,{}),/Authentication required/);
 ctx.findUserRecordBySessionToken_=()=>({user:{Username:'test-player'}}); ctx.isAdmin=()=>false;
 assert.throws(()=>ctx.apiSecurityAuthorizeRequest_('adminSaveAppearanceOverride',{token:'synthetic'}),/Admin access denied/);
 console.log('R3 safety: production/unknown/mismatched environments blocked; controller and adapter mutation guards; sanitized cached Published reads; Draft/admin authorization PASS');
}
main().catch(error=>{console.error(error);process.exitCode=1;});
