'use strict';
const assert = require('assert'), fs = require('fs'), vm = require('vm');
const R3 = require('../frontend/js/ownerVisualStudioR3.js');
const fixture = fs.readFileSync('tests/owner_visual_studio_r3_dom_tests.js','utf8');
const ctx = {require,console,__dirname}; vm.createContext(ctx);
vm.runInContext(fixture.slice(0,fixture.indexOf('const {document,Node}=dom();'))+'\nthis.makeDOM=dom;',ctx);
async function main() {
  let m = R3.normalize({pageKey:'betting',items:{section:{style:{padding:24,widthPct:90,fontSize:18},columns:3}},collapse:{section:{collapsible:true,defaultOpen:true,collapseStyle:'blind',rememberPlayerState:false}}});
  for (const view of ['desktop','tablet','mobile']) assert.equal(R3.resolveView(m,view).items.section.style.padding,24);
  const mobile = R3.responsiveLayer(m,'mobile',true), tablet = R3.responsiveLayer(m,'tablet',true);
  mobile.items.section = {style:{padding:12},columns:1}; tablet.items.section = {style:{fontSize:20}};
  mobile.hidden.section = true; mobile.collapse.section = {defaultOpen:false};
  assert.equal(R3.resolveView(m,'mobile').items.section.style.padding,12);
  assert.equal(R3.resolveView(m,'tablet').items.section.style.fontSize,20);
  assert.equal(R3.resolveView(m,'desktop').items.section.style.padding,24);
  assert(!R3.resolveView(m,'tablet').hidden.section); assert(R3.resolveView(m,'mobile').hidden.section);
  assert(R3.resolveView(m,'tablet').collapse.section.defaultOpen); assert(!R3.resolveView(m,'mobile').collapse.section.defaultOpen);
  m.items.section.style.padding = 32; m.items.section.style.fontSize = 19;
  assert.equal(R3.resolveView(m,'tablet').items.section.style.padding,32);
  assert.equal(R3.resolveView(m,'mobile').items.section.style.padding,12);
  assert.equal(R3.resolveView(m,'mobile').items.section.style.fontSize,19);
  assert.equal(R3.resolveView(m,'tablet').items.section.style.fontSize,20);
  delete mobile.items.section.style.padding;
  assert.equal(R3.resolveView(m,'mobile').items.section.style.padding,32);
  m.hidden.section = true; tablet.hidden.section = false;
  assert.equal(R3.resolveView(m,'tablet').hidden.section,false);
  assert.equal(R3.resolveView(m,'desktop').hidden.section,true);
  assert.deepEqual([600,601,1024,1025].map(R3.breakpointFor),['mobile','tablet','tablet','desktop']);
  let saved, writes = [];
  const adapter = {readFresh:async()=>({success:true,overrides:saved?[{EntityType:R3.TYPES.draft,EntityId:'betting',ThemeOverrideJSON:JSON.stringify(saved)}]:[]}),write:async(scope,type,id,value)=>{writes.push([scope,type,id]);saved=value;return {success:true};}};
  const controller=R3.createController(adapter,{setTimeout:()=>0,clearTimeout(){}});
  await controller.open({gameId:'nfl-sports-wager',pageKey:'betting'}); controller.edit(next=>Object.assign(next,m)); await controller.flush();
  assert.equal(controller.snapshot().status,'Draft Saved');
  const fresh=R3.createController(adapter);await fresh.open({gameId:'nfl-sports-wager',pageKey:'betting'});
  assert.equal(R3.exact(fresh.snapshot().manifest),R3.exact(m));assert(writes.every(x=>x[1]===R3.TYPES.draft&&x[2]==='betting'));

  const {document,Node}=ctx.makeDOM(), root=new Node('main'), section=new Node('details'), header=new Node('summary'), body=new Node('div');
  root.id='app';section.id='section';header.textContent='Header';body.textContent='Body';document.body.appendChild(root);root.appendChild(section);section.appendChild(header);section.appendChild(body);
  section.open=false; let localWrites=0;const storage=new Map();const options={storage:{getItem:k=>storage.has(k)?storage.get(k):null,setItem:(k,v)=>{localWrites++;storage.set(k,v);}}};
  let renderer=R3.createRenderer(root,options); const key=renderer.key(section), selected=renderer.key(body);
  let manifest=R3.normalize({pageKey:'betting',collapse:{[key]:{collapsible:true,defaultOpen:false,collapseStyle:'blind',rememberPlayerState:false}}});
  const context={view:'desktop',scope:'nfl-sports-wager',editing:true};
  renderer.render(manifest,context);let wrapper=section.querySelector('.r3-collapse-body');
  assert.equal(wrapper.style.getPropertyValue('max-height'),'0px');assert.equal(section.open,true);assert.strictEqual(header.parentNode,section);
  renderer.setSectionOpen(key,true);assert.equal(wrapper.style.getPropertyValue('transition'),'max-height 240ms ease');assert(!wrapper.inert);
  globalThis.matchMedia=()=>({matches:true}); renderer.setSectionOpen(key,false); assert.equal(wrapper.style.getPropertyValue('transition'),'none','Reduced motion disables blind animation'); delete globalThis.matchMedia; assert.strictEqual(renderer.find(selected),body);assert.strictEqual(renderer.find(key),section);assert.equal(localWrites,0);
  renderer.render(manifest,context);assert.equal(section.querySelector('.r3-collapse-body').style.getPropertyValue('max-height'),'0px');
  manifest.collapse[key].collapsible=false;renderer.render(manifest,context);wrapper=section.querySelector('.r3-collapse-body');assert.equal(wrapper,null);assert.strictEqual(body.parentNode,section);assert.equal(section.open,true);assert(!header.querySelector('button'));
  manifest.collapse[key]={collapsible:true,defaultOpen:true,collapseStyle:'instant',rememberPlayerState:false};renderer.render(manifest,{...context,editing:false});renderer.setSectionOpen(key,false);
  assert.equal(section.querySelector('.r3-collapse-body').style.getPropertyValue('transition'),'none');assert.equal(localWrites,0);
  renderer.reset();renderer=R3.createRenderer(root,options);renderer.render(manifest,{...context,editing:false});assert.equal(section.querySelector('.r3-collapse-body').style.getPropertyValue('max-height'),'none','OFF reload uses default');
  manifest.collapse[key].rememberPlayerState=true;renderer.render(manifest,{...context,editing:false});renderer.setSectionOpen(key,false);assert.equal(localWrites,1);
  renderer.reset();renderer=R3.createRenderer(root,options);renderer.render(manifest,{...context,editing:false});assert.equal(section.querySelector('.r3-collapse-body').style.getPropertyValue('max-height'),'0px','ON reload remembers');
  renderer.render(manifest,context);assert.equal(section.querySelector('.r3-collapse-body').style.getPropertyValue('max-height'),'none','Studio ignores player preference');
  R3.responsiveLayer(manifest,'mobile',true).collapse[key]={defaultOpen:false};renderer.render(manifest,{...context,view:'mobile'});assert.equal(section.querySelector('.r3-collapse-body').style.getPropertyValue('max-height'),'0px');assert.equal(root.style.getPropertyValue('width'),'390px');
  renderer.render(manifest,context);assert.equal(root.style.getPropertyValue('width'),'');assert.equal(section.querySelector('.r3-collapse-body').style.getPropertyValue('max-height'),'none');
  renderer.reset();assert.strictEqual(body.parentNode,section);assert.equal(section.open,false);assert(!header.querySelector('button'));
  console.log('R3 responsive/collapse: inheritance, custom overrides, reset, propagation, visibility/collapse isolation, Draft reload, ON/OFF, default states, blind/instant, selection identity, browser preference and original restoration PASS');
}
main().catch(e=>{console.error(e);process.exitCode=1;});
