#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(process.argv[2]||process.cwd());
const read=rel=>fs.readFileSync(path.join(root,rel),'utf8');
let pass=0; const ok=(v,m)=>{assert.ok(v,m);pass++;console.log('PASS:',m)};
const tf=read('backend/engines/SportsTeamFantasyEngine.js');
const surv=read('frontend/js/pages/survivor.js');
const runtime=read('frontend/js/appearanceThemeRuntime.js');
const picks=read('frontend/js/pages/picks.js');
const wager=read('frontend/js/pages/betting.js');
const api=read('backend/Api.js');
const apiJs=read('frontend/js/api.js');
const apiMirror=read('frontend/api.js');
const adminGames=read('frontend/js/pages/adminGames.js');
const purge=read('backend/engines/PermanentGamePurgeEngine.js');
const kothLeague=read('backend/engines/KingOfHillRC24ALeagueCompetitionEngine.js');
const kothFinal=read('backend/engines/KingOfHillRC24AFinalizationEngine.js');
const launch=read('frontend/js/pages/sportsLaunchCore.js');
const appHtml=read('frontend/app.html');
const indexHtml=read('frontend/index.html');
const pwa=read('frontend/js/pwa.js');
const appJs=read('frontend/js/app.js');
const appMirror=read('frontend/app.js');
const sw=read('frontend/sw.js');
ok(launch.includes('PATTCSportsLaunchCore')&&launch.includes('renderSportsHub_')&&appHtml.includes('sportsLaunchCore.js')&&appHtml.includes('rc24a-sports-launch-core.css')&&sw.includes('sportsLaunchCore.js'),'accepted Sports Launch Core prerequisite registered in app/PWA shell');
ok(tf.includes('RC24A_R47_TEAM_FANTASY_FINAL_PERSISTENCE')&&tf.includes('QualificationMethod')&&tf.includes('AutoFillScope')&&tf.includes('AutoFillWeek'),'Team Fantasy R4.7 qualification + week/season protection persistence installed');
ok(runtime.includes('RC24A_R46_SHARED_SPORTS_HERO_CONTRACT')&&runtime.includes('sportsHeroForGameHtml'),'shared Sports Hero contract installed');
ok(picks.includes('RC24A_R47_CONFIDENCE_FIVE_GAME_HERO_ADAPTER'),'Confidence consumes shared Sports Hero');
ok(picks.includes('RC24A_ROY_CONFIDENCE_STABLE_HERO_MOUNT')&&picks.includes('id=\"confidenceSportsHeroMount\"'),'Confidence shared Hero uses dedicated stable mount');
ok(picks.includes('list.innerHTML = renderCompactConfidenceSlate_();')&&!picks.includes('confidenceSharedSportsHeroHtml_() + renderCompactConfidenceSlate_()'),'Confidence appearance redraw targets compact slate only');
ok(!picks.includes('confidenceSharedSportsHeroHtml_() : \"\") + renderPicksCategoryList()'),'Confidence category-list redraw excludes shared Hero');
ok(picks.includes('refreshConfidenceSportsHero_();')&&picks.includes('refreshConfidenceAppearanceUi_();'),'Confidence appearance hydration refreshes Hero separately from slate');
ok(picks.includes('RC24A_ROY_CONFIDENCE_PLATFORM_IMAGES')&&picks.includes('confidenceRc24aLogoHtml_')&&picks.includes('platformImgHtml'),'Confidence Compare/Trend images use shared PlatformImageEngine helper');
ok(!picks.includes('<img'),'Confidence picks source contains no literal image-engine bypass');
ok(wager.includes('RC24A_R47_WAGER_SHARED_HERO'),'Sports Wager consumes shared Sports Hero');
ok(surv.includes('RC24A_R47_SURVIVOR_KOTH_SHARED_HERO')&&surv.includes('RC24A_KOTH_FINALIZATION'),'Survivor/KOTH integrated source installed');
ok(surv.includes("KOTH final renderer owns one header and now reads Kent's shared GameAppearance sportsHero values.")&&surv.includes('payload.mode === \"king-of-the-hill\") return html'),'KOTH double-Hero collision reconciled');
const survHeroBlock=surv.slice(surv.indexOf('/* RC24A_R47_SURVIVOR_KOTH_SHARED_HERO */'));
ok(survHeroBlock.includes('payload.mode === \"streak-points-strikes\"'),'Shared Survivor Hero wrapper recognizes distinct RC24A Streak Points + Strikes mode');
ok(surv.includes('appearanceRuntime.sportsHeroPresentation')&&surv.includes('kentPresentation.imageUrl')&&surv.includes('kentPresentation.title')&&surv.includes('function sportsFinalKothPageHtml_'),'KOTH final renderer consumes Kent configurable GameAppearance Hero contract');

ok(/function sportsRichSurvivorEnabled_\(payload\)[\s\S]{0,1800}PATTCSportsRich\.isRich\s*\(/.test(surv),'Survivor/KOTH activation helper retains RC23 Rich/Clean decision call while RC24A default-Rich fallback remains available');
const finalSurvivorWrapper=surv.slice(surv.lastIndexOf('renderSurvivorPage = async function()'));
ok(finalSurvivorWrapper.indexOf('await PATTCSportsRich.prepare(gameId)') >= 0 && finalSurvivorWrapper.indexOf('sportsRichSurvivorEnabled_(payload)') > finalSurvivorWrapper.indexOf('await PATTCSportsRich.prepare(gameId)'), 'final Survivor outer wrapper prepares Appearance before RC23 Rich/Clean decision');
ok(runtime.includes('RC24A_V12_OFFICIAL_SPORTS_MEDIA_DEFAULTS')&&runtime.includes('sportsHeroOfficialDefaults'),'official five-game PATTC Sports media defaults installed in shared Appearance runtime');
['team-fantasy','confidence','sports-wager','survivor','koth'].forEach(function(name){
  ok(fs.existsSync(path.join(root,'frontend/assets/sports/official/'+name+'-hero.png'))&&fs.existsSync(path.join(root,'frontend/assets/sports/official/'+name+'-logo.png')),name+' official hero + logo bundled in frontend assets');
});
ok(surv.includes('appearanceRuntime.sportsHeroPresentation')&&surv.includes('kentPresentation.imageUrl')&&surv.includes('kentPresentation.logoUrl')&&runtime.includes('koth-hero.png')&&runtime.includes('koth-logo.png'),'KOTH final single-Hero renderer consumes official default media through shared Appearance bridge');
ok(kothLeague.includes('LeagueId')&&kothLeague.includes('kothProcessWeekForLeague_'),'KOTH strike/history competition is league-aware');
ok(kothFinal.includes('kingOfHillLeaderboardDataLeague_')&&kothFinal.includes('kothHistoryRowsForLeague_'),'KOTH final read model uses league-owned standings/history');
ok(purge.includes('const PERMANENT_GAME_PURGE_PRODUCTION_ENABLED = false;')&&purge.includes('RC24B_FIXTURE_ONLY'),'Ted permanent purge destructive production path remains server-blocked');
ok(api.includes('adminPermanentGamePurgeDryRun')&&api.includes('adminPermanentGamePurge'),'Ted purge admin API routes wired into Apps Script');
ok(adminGames.includes('RC24B_MANAGE_GAMES_PURGE_DANGER_ZONE')&&adminGames.includes('Run Deletion Preview'),'Manage Games contains phone-friendly Purge Danger Zone preview');
ok(apiJs===apiMirror,'frontend API compatibility mirrors remain identical');
ok(apiJs.includes('\"adminPermanentGamePurgeDryRun\"')&&apiJs.includes('\"adminPermanentGamePurge\"'),'purge actions receive long API timeout');
const rel=(appHtml.match(/<meta\s+name=[\"']pattc-release[\"']\s+content=[\"']([^\"']+)[\"']/i)||[])[1]||'';
ok(!!rel,'canonical pattc-release exists');
ok(appJs===appMirror,'frontend app.js compatibility mirrors remain identical');
ok(indexHtml.includes('name=\"pattc-release\" content=\"'+rel+'\"')&&appHtml.includes('release='+rel)&&indexHtml.includes('release='+rel),'authenticated and login/PWA HTML shells share canonical pattc-release');
ok(appJs.includes('const APP_ASSET_VERSION = String(window.PATTC_FRONTEND_RELEASE || \"'+rel+'\");')&&pwa.includes('const PWA_VERSION = String(window.PATTC_FRONTEND_RELEASE || \"'+rel+'\");')&&sw.includes('const PATTC_SW_RELEASE_MARKER = \"'+rel+'\";'),'APP_ASSET_VERSION, PWA_VERSION, and service-worker markers match canonical pattc-release');
const legacyRc23='v1219rc23-appearance-transport-cache-r2';
ok(appHtml.includes('meta name=\"pattc-release\" content=\"'+legacyRc23+'\"')&&indexHtml.includes('meta name=\"pattc-release\" content=\"'+legacyRc23+'\"'),'RC23 HTML release lineage retained as compatibility marker');
ok(appJs.includes('window.PATTC_FRONTEND_RELEASE || \"'+legacyRc23+'\"')&&pwa.includes('window.PATTC_FRONTEND_RELEASE || \"'+legacyRc23+'\"')&&sw.includes('PATTC_SW_RELEASE_MARKER = \"'+legacyRc23+'\"'),'RC23 app/PWA/SW release lineage retained as compatibility marker');
console.log(`RESULT: ${pass} integrated Roy review checks PASS`);
