#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(process.argv[2]||process.cwd());
const read=rel=>fs.readFileSync(path.join(root,rel),'utf8');
let pass=0; const ok=(v,m)=>{assert.ok(v,m);pass++;console.log('PASS:',m)};
const tf=read('backend/engines/SportsTeamFantasyEngine.js');
const surv=read('frontend/js/pages/survivor.js');
const runtime=read('frontend/js/appearanceThemeRuntime.js');
const picks=read('frontend/js/pages/picks.js');
const wager=read('frontend/js/pages/betting.js');
const api=read('backend/Api.js');
const apiJs=read('frontend/js/api.js');
const apiMirror=read('frontend/api.js');
const adminGames=read('frontend/js/pages/adminGames.js');
const purge=read('backend/engines/PermanentGamePurgeEngine.js');
const kothLeague=read('backend/engines/KingOfHillRC24ALeagueCompetitionEngine.js');
const kothFinal=read('backend/engines/KingOfHillRC24AFinalizationEngine.js');
const launch=read('frontend/js/pages/sportsLaunchCore.js');
const appHtml=read('frontend/app.html');
const indexHtml=read('frontend/index.html');
const pwa=read('frontend/js/pwa.js');
const appJs=read('frontend/js/app.js');
const appMirror=read('frontend/app.js');
const sw=read('frontend/sw.js');
ok(launch.includes('PATTCSportsLaunchCore')&&launch.includes('renderSportsHub_')&&appHtml.includes('sportsLaunchCore.js')&&appHtml.includes('rc24a-sports-launch-core.css')&&sw.includes('sportsLaunchCore.js'),'accepted Sports Launch Core prerequisite registered in app/PWA shell');
ok(tf.includes('RC24A_R47_TEAM_FANTASY_FINAL_PERSISTENCE')&&tf.includes('QualificationMethod')&&tf.includes('AutoFillScope')&&tf.includes('AutoFillWeek'),'Team Fantasy R4.7 qualification + week/season protection persistence installed');
ok(runtime.includes('RC24A_R46_SHARED_SPORTS_HERO_CONTRACT')&&runtime.includes('sportsHeroForGameHtml'),'shared Sports Hero contract installed');
ok(picks.includes('RC24A_R47_CONFIDENCE_FIVE_GAME_HERO_ADAPTER'),'Confidence consumes shared Sports Hero');
ok(picks.includes('RC24A_ROY_CONFIDENCE_STABLE_HERO_MOUNT')&&picks.includes('id=\"confidenceSportsHeroMount\"'),'Confidence shared Hero uses dedicated stable mount');
ok(picks.includes('list.innerHTML = renderCompactConfidenceSlate_();')&&!picks.includes('confidenceSharedSportsHeroHtml_() + renderCompactConfidenceSlate_()'),'Confidence appearance redraw targets compact slate only');
ok(!picks.includes('confidenceSharedSportsHeroHtml_() : \"\") + renderPicksCategoryList()'),'Confidence category-list redraw excludes shared Hero');
ok(picks.includes('refreshConfidenceSportsHero_();')&&picks.includes('refreshConfidenceAppearanceUi_();'),'Confidence appearance hydration refreshes Hero separately from slate');
ok(picks.includes('RC24A_ROY_CONFIDENCE_PLATFORM_IMAGES')&&picks.includes('confidenceRc24aLogoHtml_')&&picks.includes('platformImgHtml'),'Confidence Compare/Trend images use shared PlatformImageEngine helper');
ok(!picks.includes('<img'),'Confidence picks source contains no literal image-engine bypass');
ok(wager.includes('RC24A_R47_WAGER_SHARED_HERO'),'Sports Wager consumes shared Sports Hero');
ok(surv.includes('RC24A_R47_SURVIVOR_KOTH_SHARED_HERO')&&surv.includes('RC24A_KOTH_FINALIZATION'),'Survivor/KOTH integrated source installed');
ok(surv.includes("KOTH final renderer owns one header and now reads Kent's shared GameAppearance sportsHero values.")&&surv.includes('payload.mode === \"king-of-the-hill\") return html'),'KOTH double-Hero collision reconciled');
const survHeroBlock=surv.slice(surv.indexOf('/* RC24A_R47_SURVIVOR_KOTH_SHARED_HERO */'));
ok(survHeroBlock.includes('payload.mode === \"streak-points-strikes\"'),'Shared Survivor Hero wrapper recognizes distinct RC24A Streak Points + Strikes mode');
ok(surv.includes('appearanceRuntime.sportsHeroPresentation')&&surv.includes('kentPresentation.imageUrl')&&surv.includes('kentPresentation.title')&&surv.includes('function sportsFinalKothPageHtml_'),'KOTH final renderer consumes Kent configurable GameAppearance Hero contract');

ok(/function sportsRichSurvivorEnabled_\(payload\)[\s\S]{0,1800}PATTCSportsRich\.appearance\(gameId, appearance\)[\s\S]{0,500}PATTCSportsRich\.layoutValue\(bundle\)[\s\S]{0,500}return layout !== "legacy";/.test(surv),'Survivor/KOTH R3 defaults to the current player layout with explicit Legacy opt-out');
const finalSurvivorWrapper=surv.slice(surv.lastIndexOf('renderSurvivorPage = async function()'));
ok(!finalSurvivorWrapper.includes('await PATTCSportsRich.prepare(gameId)') && surv.includes('Promise.resolve(PATTCSportsRich.prepare(gameId))') && finalSurvivorWrapper.includes('sportsRichSurvivorEnabled_(payload)'), 'Survivor keeps RC23 Rich/Clean decision while Appearance prepare is deferred/deduped outside the final blocking wrapper');
ok(runtime.includes('RC24A_V12_OFFICIAL_SPORTS_MEDIA_DEFAULTS')&&runtime.includes('sportsHeroOfficialDefaults'),'official five-game PATTC Sports media defaults installed in shared Appearance runtime');
['team-fantasy','confidence','sports-wager','survivor','koth'].forEach(function(name){
  ok(fs.existsSync(path.join(root,'frontend/assets/sports/official/'+name+'-hero.png'))&&fs.existsSync(path.join(root,'frontend/assets/sports/official/'+name+'-logo.png')),name+' official hero + logo bundled in frontend assets');
});
ok(surv.includes('appearanceRuntime.sportsHeroPresentation')&&surv.includes('kentPresentation.imageUrl')&&surv.includes('kentPresentation.logoUrl')&&runtime.includes('koth-hero.png')&&runtime.includes('koth-logo.png'),'KOTH final single-Hero renderer consumes official default media through shared Appearance bridge');
ok(kothLeague.includes('LeagueId')&&kothLeague.includes('kothProcessWeekForLeague_'),'KOTH strike/history competition is league-aware');
ok(kothFinal.includes('kingOfHillLeaderboardDataLeague_')&&kothFinal.includes('kothHistoryRowsForLeague_'),'KOTH final read model uses league-owned standings/history');
ok(purge.includes('const PERMANENT_GAME_PURGE_PRODUCTION_ENABLED = true;')&&purge.includes('TARGET_GAME_ACTIVE')&&purge.includes('production-write')&&purge.includes('permanentGamePurgeExecuteProduction_'),'RC24C permanent purge enables exact-confirmation production cleanup with inactive-target and production-write safety gates');
ok(api.includes('adminPermanentGamePurgeDryRun')&&api.includes('adminPermanentGamePurge'),'Ted purge admin API routes wired into Apps Script');
ok(adminGames.includes('RC24B_MANAGE_GAMES_PURGE_DANGER_ZONE')&&adminGames.includes('Run Deletion Preview'),'Manage Games contains phone-friendly Purge Danger Zone preview');
ok(apiJs===apiMirror,'frontend API compatibility mirrors remain identical');
ok(apiJs.includes('\"adminPermanentGamePurgeDryRun\"')&&apiJs.includes('\"adminPermanentGamePurge\"'),'purge actions receive long API timeout');
const rel=(appHtml.match(/<meta\s+name=[\"']pattc-release[\"']\s+content=[\"']([^\"']+)[\"']/i)||[])[1]||'';
ok(!!rel,'canonical pattc-release exists');
ok(appJs===appMirror,'frontend app.js compatibility mirrors remain identical');
const validRelease=value=>/^v\d{4,}rc\d+[a-z0-9-]*$/i.test(String(value||''));
const loginRel=(indexHtml.match(/<meta\s+name=["']pattc-release["']\s+content=["']([^"']+)["']/i)||[])[1]||'';
const appFallback=(appJs.match(/^const APP_ASSET_VERSION\s*=\s*String\(window\.PATTC_FRONTEND_RELEASE\s*\|\|\s*"([^"]+)"\)/m)||[])[1]||'';
const pwaFallback=(pwa.match(/^const PWA_VERSION\s*=\s*String\(window\.PATTC_FRONTEND_RELEASE\s*\|\|\s*"([^"]+)"\)/m)||[])[1]||'';
const swAudit=(sw.match(/^const PATTC_SW_RELEASE_MARKER\s*=\s*"([^"]+)"/m)||[])[1]||'';
ok(validRelease(rel)&&appHtml.includes('release='+rel),'authenticated shell keeps canonical pattc-release boundary');
ok(validRelease(loginRel)&&indexHtml.includes('release='+loginRel),'login/PWA shell keeps its own valid pattc-release boundary');
ok(validRelease(appFallback)&&validRelease(pwaFallback)&&validRelease(swAudit),'app/PWA/SW historical fallback and audit markers remain valid PATTC releases');
ok(appJs.includes('window.PATTC_FRONTEND_RELEASE')&&pwa.includes('window.PATTC_FRONTEND_RELEASE')&&pwa.includes('"./sw.js?v=" + encodeURIComponent(PWA_VERSION)')&&sw.includes('new URL(self.location.href).searchParams.get("v")')&&sw.includes('const AWARDS_CACHE = "awards-app-" + AWARDS_RELEASE'),'runtime release propagation and SW cache/query protections remain intact');
const legacyRc23='v1219rc23-appearance-transport-cache-r2';
ok(appHtml.includes('meta name=\"pattc-release\" content=\"'+legacyRc23+'\"')&&indexHtml.includes('meta name=\"pattc-release\" content=\"'+legacyRc23+'\"'),'RC23 HTML release lineage retained as compatibility marker');
ok(appJs.includes('window.PATTC_FRONTEND_RELEASE || \"'+legacyRc23+'\"')&&pwa.includes('window.PATTC_FRONTEND_RELEASE || \"'+legacyRc23+'\"')&&sw.includes('PATTC_SW_RELEASE_MARKER = \"'+legacyRc23+'\"'),'RC23 app/PWA/SW release lineage retained as compatibility marker');
console.log(`RESULT: ${pass} integrated Roy review checks PASS`);
