const fs=require("fs"),path=require("path"),assert=require("assert");
const root=path.resolve(__dirname,".."),r=p=>fs.readFileSync(path.join(root,p),"utf8");
const picks=r("backend/engines/PicksEngine.js"),scoring=r("backend/engines/ScoringEngine.js");
const survivor=r("backend/engines/SportsSurvivorEngine.js"),api=r("backend/Api.js"),fapi=r("frontend/js/api.js");
const fpicks=r("frontend/js/pages/picks.js"),fsurvivor=r("frontend/js/pages/survivor.js"),admin=r("frontend/js/pages/admin.js");
const html=r("frontend/app.html"),css=r("frontend/css/rc24k-nfl-player-experience.css");
assert(picks.includes("RC24K — CONFIDENCE COMPARE"));
assert(picks.includes('return status === "archived"'));
assert(picks.includes("Every Confidence row must include categoryId and nomineeId"));
assert(scoring.includes("selectedConfidence > 0"));
assert(scoring.includes("Blank confidence is the safe basic pick"));
assert(api.includes('action === "getConfidenceCompare"'));
assert(fapi.includes("function apiGetConfidenceCompare"));
assert(fpicks.includes("RC24K — NFL CONFIDENCE PLAYER EXPERIENCE"));
assert(fpicks.includes("Pick a team first"));
assert(fpicks.includes("No confidence · +1 / 0"));
assert(fpicks.includes("COMPARE PICKS"));
assert(fpicks.includes("rc24kSaveConfidenceRow_"));
assert(survivor.includes('"AutoPickEnabled"'));
assert(survivor.includes("sportsSurvivorRc24kAutoPickMissing_"));
assert(survivor.includes("best-record"));
assert(survivor.includes("best-odds"));
assert(survivor.includes('settings.mode === "streak-survivor" && settings.lossesAllowed > 0'));
assert(admin.includes('name="survivorAutoPickEnabled"'));
assert(admin.includes('name="survivorAutoPickStrategy"'));
assert(fsurvivor.includes("RC24K — NFL SURVIVOR + KOTH PLAYER EXPERIENCE"));
assert(fsurvivor.includes("lives</span>"));
assert(css.includes(".sports-default-koth-final .koth-rich-hero"));
assert(css.includes(".rc24k-confidence-compare-table"));
assert(html.includes("v1219rc24k-nfl-player-experience-r1"));
assert(html.includes("rc24k-nfl-player-experience.css"));
assert(r("frontend/js/app.js")===r("frontend/app.js"));
console.log("RC24K NFL player experience tests: PASS");
