const fs = require('fs');
const path = require('path');
const assert = require('assert');
const root = path.resolve(__dirname, '..');
const season = fs.readFileSync(path.join(root, 'backend/engines/RealityTvSeasonEngine.js'), 'utf8');
const questions = fs.readFileSync(path.join(root, 'backend/engines/RealityTvQuestionPackEngine.js'), 'utf8');
const anchor = fs.readFileSync(path.join(root, 'backend/engines/SeasonAnchorEngine.js'), 'utf8');
const appData = fs.readFileSync(path.join(root, 'backend/engines/AppDataEngine.js'), 'utf8');
const api = fs.readFileSync(path.join(root, 'backend/Api.js'), 'utf8');
const admin = fs.readFileSync(path.join(root, 'frontend/js/pages/adminRealityTv.js'), 'utf8');
const picks = fs.readFileSync(path.join(root, 'frontend/js/pages/picks.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'frontend/css/styles.css'), 'utf8');
const html = fs.readFileSync(path.join(root, 'frontend/app.html'), 'utf8');
const sw = fs.readFileSync(path.join(root, 'frontend/sw.js'), 'utf8');

assert(season.includes('RealityGroups'), 'RealityGroups normalized sheet missing');
assert(season.includes('apiAdminSaveRealityTvGroups'), 'Group save API missing');
assert(season.includes('realityTvUserGameViewPayload_'), 'User Reality TV view payload missing');
assert(api.includes('"adminSaveRealityTvGroups"'), 'Group API action not registered');
assert(appData.includes('realityTvView'), 'Startup payload does not include Reality TV view');
assert(questions.includes('LayoutType') && questions.includes('ImageSource'), 'Question display fields missing');
assert(questions.includes('realityTvResolvedQuestionLayout_'), 'Automatic layout resolver missing');
assert(questions.includes('teamColor') && questions.includes('biography'), 'Roster metadata not reused in question answers');
assert(admin.includes('Display & Images'), 'Per-question Display & Images panel missing');
assert(admin.includes('Group Images & Colors') || admin.includes('Images & Colors'), 'Group manager missing');
assert(admin.includes('apiAdminSaveRealityTvGroups'), 'Group manager save call missing');
assert(picks.includes('renderRealityTvEpisodeSections_'), 'Episode collapsible sections missing');
assert(picks.includes('realityTvProfileDetailsHtml_'), 'Expandable bio renderer missing');
assert(picks.includes('YOUR PICK'), 'User pick highlight missing');
assert(picks.includes('ELIMINATED'), 'Eliminated overlay missing');
assert(picks.includes('Pinned season feature'), 'Season Survivor is not pinned visually');
assert(anchor.includes('seasonAnchorUserHistorySummary_'), 'Detailed Survivor stats missing');
assert(css.includes('.reality-episode-picks-section'), 'Episode section CSS missing');
assert(css.includes('filter:grayscale(1)') || css.includes('filter: grayscale(1)'), 'Eliminated grayscale CSS missing');
assert(css.includes('--reality-team-color'), 'Team color border CSS missing');
assert(html.includes('v283-reality-tv-visual-roster'), 'Frontend cache version missing');
assert(sw.includes('v283-reality-tv-visual-roster'), 'Service worker cache version missing');
// v1.0.31 follow-up: main exit question and old tribe IDs are visual too.
assert(admin.includes('realityTvEliminationLayout_'), 'Existing season exit question should expose an answer display control.');
assert(admin.includes('realityTvEliminationImageSource_'), 'Existing season exit question should expose an image source control.');
assert(admin.includes('id="realityTvEliminationLayout"'), 'New season setup should expose an exit-question display control.');
assert(season.includes('EliminationLayoutType'), 'Season settings should persist the exit-question layout.');
assert(season.includes('EliminationImageSource'), 'Season settings should persist the exit-question image source.');
assert(picks.includes('id.endsWith("-" + groupName)'), 'Legacy tribe/group nominee IDs should resolve to the saved group visual profile.');
assert(picks.includes('realityTvQuestionVisual_'), 'Question-specific display/image resolver missing on Picks.');
assert(picks.includes('visual.imageSource === "none"'), 'No-images setting is not honored on Picks.');
assert(css.includes('.reality-profile-choice.reality-layout-list'), 'List display layout CSS missing.');

console.log('Reality TV visual roster and episode layout tests passed.');
