const fs=require('fs'),assert=require('assert');
const read=p=>fs.readFileSync(p,'utf8');
const be=read('backend/engines/SportsSurvivorEngine.js');
const api=read('backend/Api.js');
const app=read('frontend/app.html');
const main=read('frontend/js/app.js');
const js=read('frontend/js/pages/survivorR4.js');
const css=read('frontend/css/survivor-r4.css');
const lab=read('frontend/js/sportsTestLab.js');
assert(be.includes('SURVIVOR_R4_PLAYER_EXPERIENCE_R1'));
['best-odds','best-record','best-rank','biggest-favorite','random'].forEach(v=>assert(be.includes('"'+v+'"')));
['thursday','sunday-early','sunday-late','sunday-night','last-game'].forEach(v=>assert(be.includes('"'+v+'"')));
assert(be.includes('sportsSurvivorR4AutoPickTriggerAt_'));
assert(be.includes('autoPickTrigger'));
assert(api.includes('trigger: body.trigger'));
assert(main.includes('"survivor": ["survivor", "survivorR4"]'));
assert(js.includes('PATTC SURVIVOR R4 PLAYER EXPERIENCE R1'));
assert(js.includes('Best Sports Rank'));
assert(js.includes('Biggest Spread Favorite'));
assert(js.includes('Before Sunday early games'));
assert(js.includes('survivor-r4-selected-team'));
assert(js.includes('survivor-r4-cm-viewer'));
assert(js.includes('survivorRecoveryR4ToggleWeek_'));
assert(js.includes('pts ('));
assert(css.includes('.survivor-r4-cm-viewer'));
assert(css.includes('.henry-survivor-carousel-controls'));
assert(lab.includes('pattcSurvivorR4TestLabApply'));
assert(lab.includes('Buffalo Bills'));
assert(app.includes('v1219-survivor-r4-player-experience-r1'));
console.log('PATTC Survivor R4 Player Experience tests: PASS');
