const assert = require('assert');
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const root = path.resolve(__dirname, '..');
const core = fs.readFileSync(path.join(root, 'backend/engines/SportsTeamFantasyEngine.js'), 'utf8');
const gameDayPath = path.join(root, 'backend/engines/SportsTeamFantasyGameDayEngine.js');
const gameDay = fs.readFileSync(gameDayPath, 'utf8');
const api = fs.readFileSync(path.join(root, 'backend/Api.js'), 'utf8');
const page = fs.readFileSync(path.join(root, 'frontend/js/pages/teamFantasy.js'), 'utf8');
const admin = fs.readFileSync(path.join(root, 'frontend/js/pages/adminTeamFantasy.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'frontend/css/team-fantasy.css'), 'utf8');

assert(core.includes('usage[position] && usage[position][team.abbr]'), 'Team usage must remain per team per position.');
assert(core.includes('payload._deferFlush !== true'), 'Single-pick save must support deferred flush for batch fill.');
assert(core.includes('_deferFlush: true'), 'Auto/Random Pick must defer per-slot flushes.');
assert(core.includes('TEAM_FANTASY_GAME_DAY_BATCH_FLUSH_v1218r1') && core.includes('SpreadsheetApp.flush();'), 'Auto/Random Pick must do one final batch flush.');
assert(core.includes('.everyMinutes(5).create()'), 'Team Fantasy sync installer must use 5-minute cadence.');
assert(core.includes('teamFantasyGameDayTriggerWindow_'), 'Central sync must be gated to NFL game windows.');
assert(api.includes('getTeamFantasyGameDayState') && api.includes('adminGetTeamFantasyTestLab'), 'Game-day and Test Lab API routes must exist.');
assert(gameDay.includes('writesSheets: false'), 'Synthetic Test Lab must declare no Sheet writes.');
assert(gameDay.includes('Opponent picks remain hidden until'), 'Server-side comparison privacy contract missing.');
assert(gameDay.includes('pollAfterMs: TEAM_FANTASY_GAME_DAY_POLL_MS'), 'Game-day payload must provide 5-minute poll cadence.');
assert(gameDay.includes('TEAM_FANTASY_GAME_DAY_POLL_MS = 5 * 60 * 1000'), 'Game-day comparison poll must be five minutes.');
const lightStart = gameDay.indexOf('function apiGetTeamFantasyGameDayState');
const lightEnd = gameDay.indexOf('function teamFantasyBuildSyntheticGameDayLab_', lightStart);
const lightApi = gameDay.slice(lightStart, lightEnd);
assert(!lightApi.includes('teamFantasyFetchWeekSchedule_') && !lightApi.includes('UrlFetchApp'), 'Player comparison polling must read cached Team Fantasy rows, not hit ESPN/Sports Engine.');
assert(page.includes('TEAM_FANTASY_GAME_DAY_UI_v1218r1'), 'Player game-day UI marker missing.');
assert(page.includes('suppressLoader: options.showGlobalLoader === true ? false : true'), 'In-page Fantasy actions must bypass the global page loader.');
assert(page.includes('Run 6-Team Test Lab'), 'Admin Test Lab button missing from Team Fantasy page.');
const teamFantasyCompareSupportsTwoToSix = page.includes('Compare 2–6 teams') || (page.includes('+ Add Team') && page.includes('selected.slice(0,6)') && page.includes('selected.length<6'));
assert(teamFantasyCompareSupportsTwoToSix, '2–6 team comparison capability missing.');
assert(page.includes('Hidden until kickoff'), 'Opponent-pick privacy UI missing.');
assert(admin.includes('Install / Update 5-min Sync'), 'Admin must expose the 5-minute trigger reinstall button.');
assert(css.includes('v1.2.18r1 game-day compare + synthetic Test Lab'), 'Game-day CSS marker missing.');
assert(css.includes('.tf-compare-slot.is-live') && css.includes('.tf-compare-slot.is-final') && css.includes('.tf-compare-slot.is-upcoming'), 'Upcoming/live/final visual states missing.');

const context = { console, Date, Math, JSON, encodeURIComponent };
vm.createContext(context);
vm.runInContext(core, context, { filename: path.join(root, 'backend/engines/SportsTeamFantasyEngine.js') });
vm.runInContext(gameDay, context, { filename: gameDayPath });
const lab = context.teamFantasyBuildSyntheticGameDayLab_();
assert.strictEqual(lab.success, true, 'Synthetic Test Lab should succeed.');
assert.strictEqual(lab.synthetic, true, 'Test Lab must be synthetic.');
assert.strictEqual(lab.writesSheets, false, 'Test Lab must not write real sheets.');
assert.strictEqual(lab.allPassed, true, 'All synthetic Test Lab checks must pass.');
assert(lab.checks.some(c => c.name === 'Real scoring engine probe passes' && c.passed === true), 'Real Team Fantasy scoring probe must pass.');
assert.strictEqual(lab.compare.competitors.length, 6, 'Synthetic league must contain six teams.');
assert(lab.compare.competitors.every(c => c.slots.length === 8), 'Every synthetic team must have eight positions.');
assert.strictEqual(lab.usageExample.QB.used, 3, 'BUF QB use example must be 3/3.');
assert.strictEqual(lab.usageExample.QB.allowed, false, 'Fourth BUF QB use must be blocked.');
assert.strictEqual(lab.usageExample.RB.used, 1, 'BUF RB use must be independent at 1/3.');
assert.strictEqual(lab.usageExample.RB.allowed, true, 'BUF RB must remain available after three BUF QB uses.');
const opponent = lab.compare.competitors.find(c => c.entryId === 'test-player-2');
assert(opponent.slots.filter(s => s.status === 'upcoming').every(s => s.hidden && !s.teamAbbr), 'Opponent upcoming picks must not leak team identity.');
assert(opponent.slots.filter(s => s.status === 'live').every(s => !s.hidden && s.teamAbbr), 'Opponent live picks must reveal after kickoff.');

console.log('Team Fantasy v1.2.18r1 game-day/Test Lab tests passed.');
