/* PATTC Castle Duel R1 — authenticated Reality TV mini-game. */
var CASTLE_DUEL_GAME_ID = '';
var CASTLE_DUEL_STATE = null;
var CASTLE_DUEL_ADMIN = null;
function castleEscape_(value){return String(value===null||value===undefined?'':value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
function castleGameId_(){return CASTLE_DUEL_GAME_ID||((typeof getFrontendGameId==='function'&&getFrontendGameId())||'');}
function castleStyles_(){return `<style>
.castle-page{max-width:850px;margin:0 auto;padding:14px 12px 90px}.castle-page .card{margin:12px 0;padding:16px}.castle-page h1,.castle-page h2{margin:4px 0 12px}.castle-head{background:#241b21;color:#fff;border-radius:15px;padding:20px}.castle-head h1{color:#f4d48a}.castle-head p{color:#f2e8dd}.castle-badge{display:inline-block;border-radius:20px;padding:3px 9px;background:#ead39c;color:#3d2913;font-size:12px;font-weight:700}.castle-row{display:flex;gap:10px;align-items:center;justify-content:space-between;flex-wrap:wrap}.castle-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:10px}.castle-tile{border:1px solid #b2ac9d;border-radius:12px;padding:12px}.castle-page select,.castle-page input{max-width:100%;padding:9px;margin:5px 0;border-radius:8px}.castle-page button{min-height:40px;cursor:pointer}.castle-page button:disabled{opacity:.5}.castle-page .castle-alert{background:#fff1e9;padding:12px;border-radius:10px}.castle-page .castle-ok{background:#e4f4e9;padding:12px;border-radius:10px}.castle-page .castle-muted{opacity:.8;font-size:13px}.castle-page .castle-status{font-size:13px;font-weight:700}.castle-page details{border:1px solid #a1a1aa;border-radius:10px;padding:9px;margin-top:9px}
</style>`;}
function castleInput_(label,id,value,min,max){return `<label>${castleEscape_(label)} <input id="${castleEscape_(id)}" type="number" min="${min||0}" max="${max||10000}" value="${castleEscape_(value)}"></label>`;}
async function castleCall_(action,payload){var result=await api(action,Object.assign({gameId:castleGameId_()},payload||{}));if(!result||result.success===false)throw new Error(result&&result.error||result&&result.message||'Castle request failed');return result;}
function castleNotify_(message,error){var box=document.getElementById('castleMessage');if(box){box.className=error?'castle-alert':'castle-ok';box.textContent=message;}}
async function castleRefresh_(){if(!CASTLE_DUEL_GAME_ID)CASTLE_DUEL_GAME_ID=castleGameId_();CASTLE_DUEL_STATE=await castleCall_('castleDuelGetState');var app=document.getElementById('app');if(app)app.innerHTML=castlePlayerMarkup_(CASTLE_DUEL_STATE);}
function castlePlayerMarkup_(s){
  var p=s.player,round=s.round,cast=s.cast||[],players=s.leaderboard||[];
  var header=`<div class="castle-head"><span class="castle-badge">THE TRAITORS · CASTLE DUEL</span><h1>Enter the Castle</h1><p>Cooperate, betray, build your alliance and survive the secret murders.</p><div class="castle-row"><b>Jackpot: ${castleEscape_(s.config.jackpot)} pts</b><b>${p?'Lives: '+castleEscape_(p.lives)+' · Secret shields: '+castleEscape_(p.shield):'New player'}</b></div></div>`;
  var announcement=s.announcement&&s.announcement.events&&s.announcement.events.length?`<section class="card castle-head"><h2>The Castle Reveal · Episode ${castleEscape_(s.announcement.episode)}</h2>${s.announcement.events.map(e=>`<p><b>${castleEscape_(e.victim)}</b> ${e.source==='ABSENCE'?'missed the episode and lost 1 life.':e.lost?'was murdered and lost 1 life.':'was targeted, but a Secret Shield saved them.'} ${e.source==='HUMAN'||e.source==='BOTH'?'The human murderer remains a secret until the finale.':''}</p>`).join('')}</section>`:'';
  var notice=s.privateNotice?`<section class="card castle-alert"><h2>${s.privateNotice.source==='ABSENCE'?'Missed Castle episode':s.privateNotice.shieldUsed?'Your Secret Shield saved you!':'You have been murdered!'}</h2><p>${s.privateNotice.source==='HUMAN'||s.privateNotice.source==='BOTH'?'One of your fellow PATTC players targeted you. The murderer remains a secret until the finale.':''} ${s.privateNotice.lost?'You lost one life.':s.privateNotice.shieldUsed?'Your shield was used. No life was lost.':''}</p></section>`:'';
  var main='';
  if(!p){main=`<section class="card"><h2>Build Your Castle Five</h2><p>Select five TV contestants. Existing eliminations do not erase future finale alliance benefits.</p><div class="castle-grid">${cast.map(x=>`<label class="castle-tile"><input type="checkbox" name="castleAlliance" value="${castleEscape_(x.id)}"> <b>${castleEscape_(x.name)}</b><br><small>${x.active?'Still competing':'Eliminated'}</small></label>`).join('')}</div><button onclick="castleJoin_()">Join the Castle</button></section>`;}
  else if(!round){main='<section class="card">Your alliance is saved. The admin has not opened your first Castle episode yet.</section>';}
  else if(!s.matches.length){main='<section class="card">You are enrolled for the next Castle episode. Existing matches will not be redrawn.</section>';}
  else{main=`<section class="card"><h2>${round.finale?'The Final Three · 10 Encounters':'Episode '+castleEscape_(round.number)}</h2><p class="castle-muted">${round.status==='OPEN'?'Lock deadline: '+castleEscape_(new Date(round.lockAt).toLocaleString()):'Round results are locked.'}</p>${round.finale?`<p>Finale tokens: <b>${castleEscape_(p.finaleTokens)}</b> · Finale shield: <b>${castleEscape_(p.finaleShield)}</b> · Finale points: <b>${castleEscape_(p.finalePoints)}</b></p>`:''}</section>`+
    (round.finale?`<section class="card"><h2>Earned murder advantages</h2><p class="castle-muted">Use before locking your first finale decision.</p><div class="castle-row"><button onclick="castleAdvantage_('BANISH')">Banish a Traitor</button><select id="castleRecruit">${cast.filter(x=>p.alliance.indexOf(x.id)<0).map(x=>`<option value="${castleEscape_(x.id)}">${castleEscape_(x.name)}</option>`).join('')}</select><button onclick="castleAdvantage_('RECRUIT')">Recruit Ally</button></div></section>`:'')+
    s.matches.map(m=>castleMatchHtml_(m,round,p,players)).join('');}
  var finale=s.finale?`<section class="card"><h2>Castle Finale Reveal</h2><p><b>Champion: ${castleEscape_(s.finale.winner)}</b> · Jackpot: ${castleEscape_(s.finale.jackpot)} points</p>${s.finale.murderHistory.map(e=>`<p>Episode ${castleEscape_(e.episode)}: ${castleEscape_(e.murderer)} targeted ${castleEscape_(e.victim)}${e.shieldUsed?' (shield used)':''}.</p>`).join('')}</section>`:'';
  var table=`<section class="card"><h2>Castle Standings</h2>${players.map(x=>`<div class="castle-row"><span>${castleEscape_(x.user)}</span><span>${castleEscape_(x.lives)} lives · ${castleEscape_(x.points)} pts${x.finalePoints!==undefined?' · '+castleEscape_(x.finalePoints)+' finale pts':''}</span></div>`).join('')}</section>`;
  return castleStyles_()+`<div class="page castle-page">${header}${announcement}${notice}<div id="castleMessage" aria-live="polite"></div>${main}${finale}${table}<button onclick="castleRefresh_()">Refresh Castle</button></div>`;
}
function castleMatchHtml_(m,round,p,players){
  var id=castleEscape_(m.id),finished=m.status!=='OPEN'&&m.status!=='TARGET_REQUIRED',locked=round.status!=='OPEN';
  var title=m.kind==='MASK'?'The Masked':m.kind==='HUMAN'?'PATTC Player: '+m.opponent:m.kind==='HOST'?'The Host':m.opponent;
  var result=m.status==='SETTLED'?`<div class="castle-ok">Opponent chose ${castleEscape_(m.answer)} · You earned ${castleEscape_(m.points)} points.</div>`:'';
  var mask='';
  if(m.kind==='MASK'){
    if(m.status==='OPEN'&&!locked)mask=`<p>Randomized wager: <b>${castleEscape_(m.wager)} points</b>. Half of an accepted wager is credited to the jackpot without reducing the full stake.</p><div class="castle-row"><button onclick="castleMask_('${id}',true)" ${m.wager>0?'':'disabled'}>Accept wager & reveal</button><button onclick="castleMask_('${id}',false)">Decline</button></div>`;
    else if(m.status==='TARGET_REQUIRED'&&!locked)mask=`<div class="castle-alert"><b>MURDERER CARD — use immediately.</b><p>Choose a human target. Your identity remains secret until the finale.</p><select id="castleTarget-${id}">${players.filter(x=>x.user!==p.user&&x.lives>0).map(x=>`<option value="${castleEscape_(x.user)}">${castleEscape_(x.user)}</option>`).join('')}</select><button onclick="castleTarget_('${id}')">Confirm secret target</button></div>`;
    else if(m.outcome)mask=`<p><b>Behind the mask: ${castleEscape_(m.outcome)}</b>${m.opponent!=='The Masked'?' · '+castleEscape_(m.opponent):''}</p>`;
    else mask='<p>This encounter was declined or expired.</p>';
  }else if(m.status==='OPEN'&&!locked){
    mask=`<p>What will your opponent do?</p><select id="castleGuess-${id}"><option value="">Select prediction</option><option value="COOPERATE">Cooperate</option><option value="BETRAY">Betray</option></select><p>What will you do?</p><select id="castleChoice-${id}"><option value="">Select decision</option><option value="COOPERATE">Cooperate</option><option value="BETRAY">Betray</option></select>`;
    if(round.finale)mask+=`<p>Optional power: <select id="castleToken-${id}"><option value="">None</option><option value="CLUE">75% clue (1 token)</option><option value="DOUBLE">Double positive points (1 token)</option><option value="SHIELD">Protection (2 tokens)</option></select><button onclick="castleToken_('${id}')">Use selected token</button></p>`;
    mask+=`<button onclick="castleSubmit_('${id}')">Lock my decision</button>`;
  }else if(m.status==='LOCKED')mask='<p class="castle-ok">Decision locked. Opponent answer remains secret until settlement.</p>';
  return `<section class="card"><div class="castle-row"><h2>Encounter ${castleEscape_(m.number)} · ${castleEscape_(title)}</h2><span class="castle-badge">${castleEscape_(m.status)}</span></div>${m.clue?`<p class="castle-ok"><b>${m.allied?'Alliance Insight':'Finale token clue'}:</b> Your opponent may ${castleEscape_(m.clue)} (75% accurate). ${m.allied?'Correct prediction: +10 alliance points.':''}</p>`:''}${mask}${result}</section>`;
}
async function castleAction_(action,payload,successMessage){try{await castleCall_(action,payload);await castleRefresh_();castleNotify_(successMessage||'Castle updated.');}catch(e){castleNotify_(e.message,true);}}
async function castleJoin_(){var selected=Array.from(document.querySelectorAll('input[name="castleAlliance"]:checked')).map(x=>x.value);if(selected.length!==5){castleNotify_('Choose exactly five different contestants.',true);return;}await castleAction_('castleDuelJoin',{alliance:selected},'Your Castle Five is saved.');}
async function castleSubmit_(id){var guess=document.getElementById('castleGuess-'+id).value,choice=document.getElementById('castleChoice-'+id).value;if(!guess||!choice){castleNotify_('Choose both your prediction and your decision.',true);return;}await castleAction_('castleDuelSubmit',{roundKey:CASTLE_DUEL_STATE.round.key,matchId:id,guess:guess,choice:choice},'Your decision is locked.');}
async function castleMask_(id,accept){if(accept&&!window.confirm('Accept this wager? Your opponent will be revealed immediately.'))return;await castleAction_('castleDuelMaskedAccept',{roundKey:CASTLE_DUEL_STATE.round.key,matchId:id,accept:accept},accept?'Your Masked opponent was revealed.':'You declined the Masked encounter.');}
async function castleTarget_(id){var el=document.getElementById('castleTarget-'+id);if(!el||!el.value){castleNotify_('No eligible human target is available.',true);return;}if(!window.confirm('Use your Murderer Card against '+el.value+'? Your selection cannot be changed.'))return;await castleAction_('castleDuelTarget',{roundKey:CASTLE_DUEL_STATE.round.key,matchId:id,targetUsername:el.value},'Your secret target is recorded.');}
async function castleToken_(id){var power=document.getElementById('castleToken-'+id).value;if(!power)return;await castleAction_('castleDuelFinaleToken',{matchId:id,power:power},'Finale power activated.');}
async function castleAdvantage_(power){var data={power:power};if(power==='RECRUIT')data.contestantId=document.getElementById('castleRecruit').value;await castleAction_('castleDuelFinaleAdvantage',data,'Your secret murder advantage has been applied.');}
async function renderCastleDuelPage(){try{CASTLE_DUEL_GAME_ID=getFrontendGameId()||CASTLE_DUEL_GAME_ID;CASTLE_DUEL_STATE=await castleCall_('castleDuelGetState');return castlePlayerMarkup_(CASTLE_DUEL_STATE);}catch(e){return castleStyles_()+`<div class="page castle-page"><section class="card"><h1>Castle Duel</h1><p>${castleEscape_(e.message)}</p><button onclick="navigate('season-hub')">Back to season</button></section></div>`;}}
/* Admin-only controls. The API, not the browser, enforces admin authorization. */
async function renderAdminCastleDuelPage(){
  try{
    var res=await apiAdminGetRealityTvDashboardSummary(),seasons=(res.seasons||[]).map(x=>x.season||x).filter(x=>x.GameId);
    CASTLE_DUEL_ADMIN=seasons;CASTLE_DUEL_GAME_ID=seasons.some(x=>x.GameId===CASTLE_DUEL_GAME_ID)?CASTLE_DUEL_GAME_ID:seasons.some(x=>x.GameId===getFrontendGameId())?getFrontendGameId():seasons[0]&&seasons[0].GameId||'';
    return castleStyles_()+`<div class="page castle-page"><h1>Castle Duel · Admin</h1><section class="card"><label>Reality TV season <select id="castleAdminGame" onchange="castleAdminSelect_(this.value)">${seasons.map(s=>`<option value="${castleEscape_(s.GameId)}" ${s.GameId===CASTLE_DUEL_GAME_ID?'selected':''}>${castleEscape_(s.SeasonName||s.GameId)}</option>`).join('')}</select></label><p class="castle-muted">Uses the selected season's official contestant roster and episode results.</p><div id="castleAdminPanel"></div><div id="castleMessage" aria-live="polite"></div></section><button onclick="navigate('admin-reality-tv')">Back to Reality TV Manager</button></div>`;
  }catch(e){return castleStyles_()+`<div class="page castle-page"><h1>Castle Duel Admin</h1><p>${castleEscape_(e.message)}</p></div>`;}
}
async function castleAdminSelect_(gameId){CASTLE_DUEL_GAME_ID=gameId;var el=document.getElementById('castleAdminPanel');if(!el)return;try{var cfg=await castleCall_('adminCastleDuelGetSettings');el.innerHTML=castleAdminMarkup_(cfg.config,cfg.cast,cfg.rounds);}catch(e){el.innerHTML=castleAdminMarkup_(null,[],[])+`<p class="castle-muted">${castleEscape_(e.message)} Save to initialize this Castle Duel.</p>`;}}
function castleAdminMarkup_(config,cast,rounds){var c=config||{encounters:3,lives:3,startingPoints:100,weeklyJackpot:100,startingJackpot:0,maskChance:15,hostChance:10,lateEntryCutoff:5,minEpisodesFinale:2,humanChance:50,maxShields:1,murderBonus:20,roles:{},finaleCounts:{faithful:2,traitor:2,allianceFaithful:1,allianceTraitor:1,allianceAny:1,former:2,host:1,mask:0,guard:0}};
  var fields=[['encounters','Duels per episode',1,10],['lives','Starting lives',1,10],['startingPoints','Starting wallet',0,10000],['weeklyJackpot','Jackpot per episode',0,10000],['maskChance','Masked draw %',0,100],['hostChance','Host draw %',0,100],['humanChance','Human draw preference %',0,100],['lateEntryCutoff','Last join episode',1,100],['minEpisodesFinale','Min episodes to qualify',1,100],['maxShields','Max secret shields',0,5],['murderBonus','Finale murder credit bonus',0,1000]];
  var counts=Object.keys(c.finaleCounts),keys={faithful:'Faithful contestants',traitor:'TV Traitors',allianceFaithful:'Alliance: Faithful',allianceTraitor:'Alliance: Traitors',allianceAny:'Alliance: Random',former:'Former human players (Guard fallback)',host:'Host',mask:'Masked',guard:'Castle Guards'};
  return `<h2>Game Settings</h2><div class="castle-grid">${fields.map(x=>castleInput_(x[1], 'castleCfg-'+x[0],c[x[0]],x[2],x[3])).join('')}</div><details><summary>Final Three · 10 encounter types</summary><div class="castle-grid">${counts.map(k=>castleInput_(keys[k], 'castleCount-'+k,c.finaleCounts[k],0,10)).join('')}</div></details><details><summary>Revealed TV roles (admin only)</summary><p class="castle-muted">Select only roles already revealed to viewers. UNKNOWN contestants have no Traitor murder power until updated.</p>${cast.map(x=>`<label class="castle-row">${castleEscape_(x.name)} <select class="castleRole" data-id="${castleEscape_(x.id)}"><option value="UNKNOWN" ${(c.roles[x.id]||'UNKNOWN')==='UNKNOWN'?'selected':''}>Unknown</option><option value="FAITHFUL" ${c.roles[x.id]==='FAITHFUL'?'selected':''}>Faithful</option><option value="TRAITOR" ${c.roles[x.id]==='TRAITOR'?'selected':''}>Traitor</option></select></label>`).join('')}</details><button onclick="castleAdminSave_()">Save Castle Settings</button><hr><h2>Episode Controls</h2><label>Lock deadline <input type="datetime-local" id="castleDeadline"></label><div class="castle-row"><button onclick="castleAdminAction_('adminCastleDuelOpenRound',true)">Open Next Episode</button><button onclick="castleAdminAction_('adminCastleDuelSettleRound',false)">Settle Locked Episode</button></div><details><summary>Final Three · 10 encounters</summary><div class="castle-row"><button onclick="castleAdminAction_('adminCastleDuelOpenFinale',true)">Open Final Three</button><button onclick="castleAdminAction_('adminCastleDuelSettleFinale',false)">Settle Finale</button></div></details><p class="castle-muted">Existing rounds: ${rounds.map(r=>castleEscape_(r.key+' '+r.status)).join(' · ')||'None'}. All actions use the isolated Castle Duel sheets; no automatic production updates.</p>`;
}
async function castleAdminSave_(){try{var payload={};['encounters','lives','startingPoints','weeklyJackpot','maskChance','hostChance','humanChance','lateEntryCutoff','minEpisodesFinale','maxShields','murderBonus'].forEach(k=>payload[k]=Number(document.getElementById('castleCfg-'+k).value));var keys=['faithful','traitor','allianceFaithful','allianceTraitor','allianceAny','former','host','mask','guard'];payload.finaleCounts={};keys.forEach(k=>payload.finaleCounts[k]=Number(document.getElementById('castleCount-'+k).value));payload.roles={};document.querySelectorAll('.castleRole').forEach(el=>payload.roles[el.dataset.id]=el.value);await castleCall_('adminCastleDuelConfigure',payload);castleNotify_('Settings saved.');await castleAdminSelect_(CASTLE_DUEL_GAME_ID);}catch(e){castleNotify_(e.message,true);}}
async function castleAdminAction_(name,requiresDeadline){try{if(!window.confirm('Run '+name+' for the selected Castle Duel game?'))return;var payload={};if(requiresDeadline){var el=document.getElementById('castleDeadline');if(!el.value)throw new Error('Choose a lock deadline first.');payload.lockAt=new Date(el.value).toISOString();}var result=await castleCall_(name,payload);castleNotify_('Action completed: '+(result.round||result.winner||'Castle updated.'));await castleAdminSelect_(CASTLE_DUEL_GAME_ID);}catch(e){castleNotify_(e.message,true);}}
// New admin panel loads after the initial page HTML has mounted.
function castleAdminHydrate_(){if(document.getElementById('castleAdminPanel'))castleAdminSelect_(CASTLE_DUEL_GAME_ID);}
