/* PATTC Castle Duel — Special Encounter Card Pack R1
 * Presentation-only visual components. No backend calls, rules, scoring,
 * authorization, sealed-result logic, or routing live in this file.
 */
(function(root){
  'use strict';

  var STYLE = String.raw`
  .csec-root{--ink:#f4ead5;--muted:#bcb09b;--gold:#c9a764;--gold2:#8f733f;--burg:#722d34;--burg2:#411a20;--panel:rgba(16,14,14,.76);--panel2:rgba(31,24,21,.62);--line:rgba(214,185,126,.38);--paper:#d6c29a;--shadow:rgba(0,0,0,.48);color:var(--ink);font-family:Georgia,'Times New Roman',serif}
  .csec-root *{box-sizing:border-box}.csec-root button{font:inherit}.csec-stack{display:grid;gap:12px}.csec-card{position:relative;overflow:hidden;border:1px solid var(--line);border-radius:5px;background:linear-gradient(135deg,rgba(20,17,15,.87),rgba(18,15,15,.65));box-shadow:0 10px 28px var(--shadow);isolation:isolate}.csec-card:before{content:"";position:absolute;inset:0;pointer-events:none;background:linear-gradient(105deg,rgba(255,255,255,.025),transparent 28%,rgba(201,167,100,.04));z-index:-1}.csec-room{position:absolute;inset:0;z-index:-2;background:radial-gradient(circle at 50% 20%,rgba(196,150,82,.22),transparent 33%),linear-gradient(180deg,#30251f 0,#171313 57%,#0d0b0c 100%)}
  .csec-room--masked{background:radial-gradient(circle at 50% 14%,rgba(133,113,153,.2),transparent 31%),linear-gradient(180deg,#28242f,#15131a 59%,#0a090d)}.csec-room--traitor{background:radial-gradient(circle at 50% 13%,rgba(118,33,43,.27),transparent 34%),linear-gradient(180deg,#2a181a,#130f11 60%,#090809)}.csec-room--host{background:radial-gradient(circle at 65% 17%,rgba(190,126,61,.24),transparent 35%),linear-gradient(180deg,#38281f,#171210 62%,#0b0908)}.csec-room--finale{background:radial-gradient(circle at 50% 8%,rgba(190,151,73,.25),transparent 30%),linear-gradient(180deg,#332123,#151012 58%,#090708)}
  .csec-kicker{font-family:Arial,Helvetica,sans-serif;font-size:10px;letter-spacing:.18em;text-transform:uppercase;color:#d5bd8b}.csec-title{font-size:21px;line-height:1.05;margin:2px 0 0;font-weight:600}.csec-sub{color:var(--muted);font-size:12px;line-height:1.35}.csec-meta{font-family:Arial,Helvetica,sans-serif;font-size:10px;color:#d1c5ae;letter-spacing:.06em;text-transform:uppercase}.csec-tag{display:inline-flex;align-items:center;min-height:22px;padding:3px 7px;border:1px solid rgba(211,184,128,.45);border-radius:4px;background:rgba(17,14,13,.45);font:700 9px/1.1 Arial,sans-serif;letter-spacing:.12em;text-transform:uppercase;color:#e4d3ae}
  .csec-btn{min-height:44px;padding:9px 13px;border:1px solid rgba(215,184,119,.55);border-radius:4px;background:rgba(88,65,40,.15);color:#f2e6cf;font:700 11px/1 Arial,sans-serif;letter-spacing:.11em;text-transform:uppercase}.csec-btn--burg{border-color:rgba(154,76,82,.7);background:rgba(103,39,44,.22)}.csec-btn--selected{background:rgba(154,120,66,.24);box-shadow:inset 0 0 0 1px rgba(227,194,126,.55)}
  .csec-portrait{position:relative;overflow:hidden;border:1px solid rgba(216,187,129,.45);border-radius:4px;background:#171413}.csec-portrait img{display:block;width:100%;height:100%;object-fit:cover}.csec-portrait:after{content:"";position:absolute;inset:0;box-shadow:inset 0 0 30px rgba(0,0,0,.48);pointer-events:none}.csec-silhouette{width:100%;height:100%;display:grid;place-items:center;background:radial-gradient(circle at 50% 28%,#40383b 0 15%,transparent 16%),radial-gradient(ellipse at 50% 78%,#3a3235 0 29%,transparent 30%),linear-gradient(180deg,#221f24,#0f0d10);color:#8f8688;font:700 30px/1 Georgia,serif}.csec-mask{font-size:22px;letter-spacing:.08em}.csec-seal{display:inline-grid;place-items:center;width:40px;height:40px;border-radius:50%;background:radial-gradient(circle at 36% 28%,#9f3d47,#6f222c 55%,#43131a 100%);border:1px solid #b06467;box-shadow:0 2px 6px rgba(0,0,0,.45),inset 0 0 0 3px rgba(67,19,26,.26);font:700 9px/1 Arial,sans-serif;letter-spacing:.07em;color:#f4d8cf;text-align:center}
  .csec-random{min-height:242px;padding:14px}.csec-random-grid{display:grid;grid-template-columns:112px 1fr;gap:14px;align-items:center;margin-top:13px}.csec-random .csec-portrait{height:154px}.csec-nameplate{border-top:1px solid rgba(207,174,109,.48);border-bottom:1px solid rgba(207,174,109,.2);padding:10px 0}.csec-name{font-size:24px;line-height:1.02}.csec-name--player{font-family:Arial,Helvetica,sans-serif;font-weight:700;letter-spacing:.02em}.csec-name--host{letter-spacing:.08em;text-transform:uppercase}.csec-roomaccent{position:absolute;right:9px;top:9px;width:45px;height:45px;border-top:1px solid rgba(202,168,99,.35);border-right:1px solid rgba(202,168,99,.35)}
  .csec-candidate{display:grid;grid-template-columns:74px 1fr 25px;gap:10px;padding:9px;align-items:center}.csec-candidate .csec-portrait{width:74px;height:88px}.csec-radio{width:20px;height:20px;border:1px solid rgba(220,193,139,.62);border-radius:50%;display:grid;place-items:center}.csec-candidate.is-selected{border-color:rgba(211,170,91,.75);background:linear-gradient(90deg,rgba(116,80,39,.2),rgba(68,29,33,.14))}.csec-candidate.is-selected .csec-radio:after{content:"";width:10px;height:10px;border-radius:50%;background:#caa45f}.csec-suspect{position:absolute;inset:0;pointer-events:none;background:radial-gradient(circle at 85% 22%,rgba(119,31,39,.23),transparent 29%)}
  .csec-revealed{display:grid;grid-template-columns:126px 1fr;min-height:190px}.csec-revealed .csec-portrait{margin:12px;width:114px;height:166px}.csec-revealed-copy{padding:16px 14px 14px;border-left:1px solid rgba(155,59,67,.45);background:linear-gradient(90deg,rgba(90,24,31,.21),transparent)}.csec-revealed-word{font:800 11px/1 Arial,sans-serif;letter-spacing:.18em;color:#e3b1ad}.csec-revealed-role{font-size:28px;line-height:.95;margin:8px 0;color:#f2d8cf}.csec-revealed-role span{display:block;font-size:14px;color:#cf938f;letter-spacing:.13em}
  .csec-masked{padding:14px;min-height:220px}.csec-masked-stage{display:grid;grid-template-columns:102px 1fr;gap:13px;align-items:center;margin-top:12px}.csec-masked .csec-portrait{height:132px}.csec-wager{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:9px}.csec-wager button{min-height:38px;padding:6px}.csec-reveal-line{height:1px;background:linear-gradient(90deg,transparent,#9c87a9,transparent);margin:10px 0}
  .csec-fate{display:grid;grid-template-columns:1fr 1fr;gap:9px}.csec-fate-card{min-height:124px;padding:13px;display:flex;flex-direction:column;justify-content:flex-end}.csec-fate-card--murdered{background:linear-gradient(155deg,rgba(79,19,25,.6),rgba(17,13,14,.85))}.csec-fate-card--spared{background:linear-gradient(155deg,rgba(77,67,46,.48),rgba(17,14,13,.86))}.csec-fate-word{font-size:24px;line-height:1}.csec-fate-mark{position:absolute;right:12px;top:10px;font-size:26px;color:#d5b36f;opacity:.76}
  .csec-murderer{padding:13px}.csec-secret{display:flex;gap:9px;align-items:center;padding:8px 0 10px;border-bottom:1px solid rgba(135,52,59,.38)}.csec-secret-icon{width:29px;height:29px;display:grid;place-items:center;border:1px solid rgba(162,76,82,.56);border-radius:50%;color:#d9aaa7;font:700 14px/1 Arial}.csec-targets{display:grid;gap:7px;margin-top:10px}.csec-target{display:grid;grid-template-columns:40px 1fr auto;gap:9px;align-items:center;padding:6px;border:1px solid rgba(211,183,127,.23);border-radius:4px;background:rgba(12,11,11,.31)}.csec-target .csec-portrait{width:40px;height:46px}.csec-target button{min-height:36px;padding:5px 9px}
  .csec-envelope-grid{display:grid;grid-template-columns:1fr;gap:9px}.csec-envelope{position:relative;min-height:128px;padding:14px 14px 12px;background:linear-gradient(145deg,#c7b389,#9d8965);color:#2e241d;border:1px solid #d9c598;border-radius:4px;box-shadow:0 8px 18px rgba(0,0,0,.35)}.csec-envelope:before,.csec-envelope:after{content:"";position:absolute;left:0;right:0;top:0;height:56%;clip-path:polygon(0 0,50% 100%,100% 0);background:rgba(234,218,181,.22);pointer-events:none}.csec-envelope:after{top:auto;bottom:0;height:47%;clip-path:polygon(0 100%,50% 0,100% 100%);background:rgba(87,67,46,.12)}.csec-envelope strong{position:relative;z-index:2;display:block;font-size:25px;letter-spacing:.08em}.csec-envelope small{position:relative;z-index:2;font:700 9px/1.2 Arial,sans-serif;letter-spacing:.13em}.csec-envelope .csec-seal{position:absolute;z-index:3;right:15px;bottom:12px}.csec-envelope--protection{background:linear-gradient(145deg,#beb8aa,#837f76)}.csec-envelope--mercy{background:linear-gradient(145deg,#c9a6a7,#9c7578)}
  .csec-ally{display:grid;grid-template-columns:88px 1fr;gap:11px;padding:10px}.csec-ally .csec-portrait{height:110px}.csec-ally-badge{display:inline-flex;align-items:center;gap:5px;font:800 9px/1 Arial,sans-serif;letter-spacing:.12em;text-transform:uppercase;color:#e6c981}.csec-ally-badge:before{content:"V";display:grid;place-items:center;width:22px;height:22px;border:1px solid #b89450;border-radius:50%;font-family:Georgia,serif}.csec-ally.is-eliminated{filter:saturate(.42);opacity:.72}.csec-ally.is-eliminated .csec-portrait:before{content:"ELIMINATED";position:absolute;z-index:3;left:4px;right:4px;top:44%;padding:4px;background:rgba(63,21,25,.86);text-align:center;font:700 8px/1 Arial;letter-spacing:.11em;color:#f1d9d5}
  .csec-history{display:grid;grid-template-columns:39px minmax(0,1fr) 48px;gap:7px;align-items:center;padding:8px 9px}.csec-episode{font:800 10px/1 Arial,sans-serif;letter-spacing:.08em}.csec-history-main{min-width:0}.csec-history-line{display:flex;gap:5px;align-items:baseline;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:11px}.csec-history-line b{font-family:Arial,sans-serif;font-size:9px;color:#c8b695;text-transform:uppercase}.csec-points{text-align:right;font:800 12px/1 Arial,sans-serif;color:#dfbf78}
  .csec-sealed{display:grid;grid-template-columns:1fr 52px;gap:9px;align-items:center;padding:11px}.csec-sealed h3{margin:0;font-size:19px;line-height:.95}.csec-sealed h3 span{display:block;color:#b8a889;font-size:13px;letter-spacing:.08em}.csec-sealed-copy{margin-top:7px;font-size:11px;color:#d7c9af}.csec-sealed .csec-seal{width:46px;height:46px}
  .csec-finale{padding:13px;min-height:190px}.csec-throne{position:absolute;right:13px;top:12px;width:62px;height:78px;border:1px solid rgba(201,165,92,.36);clip-path:polygon(18% 0,36% 19%,50% 3%,64% 19%,82% 0,76% 40%,100% 100%,0 100%,24% 40%);background:linear-gradient(180deg,rgba(177,138,67,.17),rgba(103,43,50,.18))}.csec-finale-content{position:relative;z-index:2;max-width:77%;padding-top:42px}.csec-finale .csec-title{font-size:27px}.csec-finale-actions{display:flex;gap:7px;margin-top:11px}.csec-finale-actions .csec-btn{flex:1}
  @media(min-width:390px){.csec-random-grid{grid-template-columns:126px 1fr}.csec-random .csec-portrait{height:166px}.csec-envelope-grid{grid-template-columns:repeat(3,1fr)}.csec-envelope{min-height:142px;padding:12px}.csec-envelope strong{font-size:20px}.csec-envelope .csec-seal{right:8px;bottom:8px;width:34px;height:34px;font-size:8px}}
  `;

  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function portrait(opt){opt=opt||{};if(opt.hidden)return '<div class="csec-portrait"><div class="csec-silhouette'+(opt.mask?' csec-mask':'')+'">'+(opt.mask?'MASK':'?')+'</div></div>';var img=opt.image||'';return '<div class="csec-portrait">'+(img?'<img src="'+esc(img)+'" alt="'+esc(opt.alt||'')+'">':'<div class="csec-silhouette">'+esc((opt.initials||'?').slice(0,2))+'</div>')+'</div>';}
  function room(cls){return '<div class="csec-room '+(cls||'')+'"></div>';}
  function randomizer(o){o=o||{};var type=o.type||'contestant', label=type==='player'?'PATTC PLAYER':type==='host'?'HOST':type==='mask'?'MASKED ENCOUNTER':type==='hidden'?'HIDDEN FIGURE':'TV CONTESTANT';var n=o.name||(type==='host'?'THE HOST':type==='mask'?'Unknown':type==='hidden'?'A Shadow':'Contestant Name');return '<article class="csec-card csec-random">'+room(o.roomClass)+'<span class="csec-roomaccent"></span><div class="csec-kicker">'+esc(o.room||'Portrait Gallery')+'</div><div class="csec-random-grid">'+portrait({image:o.image,hidden:type==='hidden'||type==='mask',mask:type==='mask',initials:o.initials})+'<div><span class="csec-tag">'+label+'</span><div class="csec-nameplate"><div class="csec-name '+(type==='player'?'csec-name--player':type==='host'?'csec-name--host':'')+'">'+esc(n)+'</div></div><p class="csec-sub">'+esc(o.copy||'The Castle has made its choice.')+'</p></div></div></article>';}
  function candidate(o){o=o||{};return '<article class="csec-card csec-candidate'+(o.selected?' is-selected':'')+'">'+room('csec-room--traitor')+'<div class="csec-suspect"></div>'+portrait({image:o.image,initials:o.initials})+'<div><div class="csec-kicker">Traitor Guess</div><div class="csec-title">'+esc(o.name||'Candidate')+'</div><div class="csec-sub">Choose based on what you know — no role information is shown.</div></div><div class="csec-radio" aria-hidden="true"></div></article>';}
  function revealedTraitor(o){o=o||{};return '<article class="csec-card csec-revealed">'+room('csec-room--traitor')+portrait({image:o.image,initials:o.initials})+'<div class="csec-revealed-copy"><div class="csec-revealed-word">ROLE AUTHORIZED FOR REVEAL</div><div class="csec-revealed-role">'+esc(o.name||'Contestant')+'<span>REVEALED TRAITOR</span></div><p class="csec-sub">Presentation only. The game must authorize this state before rendering it.</p></div></article>';}
  function masked(o){o=o||{};return '<article class="csec-card csec-masked">'+room('csec-room--masked')+'<div class="csec-kicker">The Masked Hall</div><div class="csec-masked-stage">'+portrait({hidden:!o.revealed,mask:!o.revealed,image:o.image,initials:o.initials})+'<div><div class="csec-title">'+(o.revealed?esc(o.name||'Figure Revealed'):'Who stands behind the mask?')+'</div><div class="csec-reveal-line"></div><div class="csec-sub">'+(o.revealed?'The wager is locked. The figure can now be shown.':'Set the wager before the Castle opens the door.')+'</div><div class="csec-wager"><button class="csec-btn">1</button><button class="csec-btn csec-btn--selected">3</button><button class="csec-btn">5</button></div></div></div></article>';}
  function fate(type){var murdered=type==='murdered';return '<article class="csec-card csec-fate-card '+(murdered?'csec-fate-card--murdered':'csec-fate-card--spared')+'"><span class="csec-fate-mark">'+(murdered?'†':'✦')+'</span><div class="csec-kicker">Fate Card</div><div class="csec-fate-word">'+(murdered?'Murdered':'Spared')+'</div><div class="csec-sub">'+(murdered?'The Castle has claimed a player.':'The Castle lets you pass — for now.')+'</div></article>';}
  function murderer(o){o=o||{};var targets=o.targets||[];return '<article class="csec-card csec-murderer">'+room('csec-room--traitor')+'<div class="csec-kicker">Secret Encounter</div><div class="csec-secret"><span class="csec-secret-icon">!</span><div><div class="csec-title">You are the Murderer</div><div class="csec-sub">Your identity remains secret. Choose one eligible PATTC target.</div></div></div><div class="csec-targets">'+targets.map(function(t){return '<div class="csec-target">'+portrait({image:t.image,initials:t.initials})+'<div><div class="csec-meta">Eligible Target</div><strong>'+esc(t.name)+'</strong></div><button class="csec-btn csec-btn--burg">Choose</button></div>';}).join('')+'</div></article>';}
  function envelopes(){return '<div class="csec-envelope-grid">'+[['gold','GOLD','GOLD'],['protection','PROTECTION','PROTECT'],['mercy','MERCY','MERCY']].map(function(x){return '<article class="csec-envelope csec-envelope--'+x[0]+'"><small>HOST REWARD</small><strong>'+x[1]+'</strong><span class="csec-seal">'+x[2]+'</span></article>';}).join('')+'</div>';}
  function ally(o){o=o||{};return '<article class="csec-card csec-ally'+(o.eliminated?' is-eliminated':'')+'">'+room()+portrait({image:o.image,initials:o.initials})+'<div><div class="csec-ally-badge">Castle Five Ally</div><div class="csec-title">'+esc(o.name||'Ally')+'</div><div class="csec-sub">'+(o.eliminated?'Eliminated':'Active ally')+' · '+esc(o.encounters==null?2:o.encounters)+' encounters</div><div class="csec-meta" style="margin-top:8px">'+(o.eliminated?'History remains visible':'Eligible for future ally encounters')+'</div></div></article>';}
  function history(o){o=o||{};return '<article class="csec-card csec-history"><div class="csec-episode">EP '+esc(o.episode||'4')+'</div><div class="csec-history-main"><div class="csec-history-line"><b>Prediction</b> '+esc(o.prediction||'Trust')+'</div><div class="csec-history-line"><b>Decision</b> '+esc(o.decision||'Share clue')+' · <b>Result</b> '+esc(o.result||'Correct')+'</div></div><div class="csec-points">'+esc(o.points||'+3')+'</div></article>';}
  function sealed(o){o=o||{};return '<article class="csec-card csec-sealed">'+room()+'<div><div class="csec-kicker">Castle Record</div><h3>Decision<span>Sealed</span></h3><div class="csec-sealed-copy">Prediction: '+esc(o.prediction||'Trust')+'<br>Decision: '+esc(o.decision||'Protect the ally')+'</div></div><span class="csec-seal">SEALED</span></article>';}
  function finale(o){o=o||{};return '<article class="csec-card csec-finale">'+room('csec-room--finale')+'<div class="csec-throne"></div><div class="csec-finale-content"><div class="csec-kicker">The Throne Room · Finale</div><div class="csec-title">'+esc(o.title||'The Final Encounter')+'</div><div class="csec-sub">'+esc(o.copy||'One last choice. The room is watching.')+'</div><div class="csec-finale-actions"><button class="csec-btn">Hold</button><button class="csec-btn csec-btn--burg">Commit</button></div></div></article>';}

  var api={style:STYLE,randomizer:randomizer,candidate:candidate,revealedTraitor:revealedTraitor,masked:masked,fate:fate,murderer:murderer,envelopes:envelopes,ally:ally,history:history,sealed:sealed,finale:finale,portrait:portrait};
  root.CastleSpecialEncounterCardsR1=api;
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
