/* PATTC Castle Duel R3 — swipe rooms, sealed decisions, Banish pressure,
 * hidden Traitor identity reads and Masked Hall card games.
 * Loaded after castleDuelRevealR2.js; backend remains authoritative.
 */

var CASTLE_DUEL_R2_SWIPE_PANELS = {};
var CASTLE_DUEL_R2_CONFIRMING = {};
var CASTLE_DUEL_R2_SUBMITTING = {};
var CASTLE_DUEL_R2_TOUCH = null;
var CASTLE_DUEL_R3_TRAITOR_GUESSES = {};

function castleR3ActiveStatus_(status){return ['OPEN','IDENTIFY_REQUIRED','FATE_REQUIRED','HOST_REQUIRED','MASK_DUEL_REQUIRED','TARGET_REQUIRED'].indexOf(String(status||'').toUpperCase())!==-1;}
function castleR2EnsureState_(s){
  var round=s&&s.round,matches=s&&Array.isArray(s.matches)?s.matches:[],key=round?String(round.key||''):'';
  if(key!==CASTLE_DUEL_R2_ROUND_KEY){
    CASTLE_DUEL_R2_ROUND_KEY=key;CASTLE_DUEL_R2_DRAFTS={};CASTLE_DUEL_R2_SUMMARY=!!(round&&String(round.status||'').toUpperCase()==='SETTLED');CASTLE_DUEL_R2_ROOM_INDEX=0;
    if(!CASTLE_DUEL_R2_SUMMARY&&matches.length){var firstActive=matches.findIndex(function(m){return castleR3ActiveStatus_(m.status);});CASTLE_DUEL_R2_ROOM_INDEX=firstActive>=0?firstActive:matches.length;if(firstActive<0)CASTLE_DUEL_R2_SUMMARY=true;}
  }
  if(CASTLE_DUEL_R2_ROOM_INDEX<0)CASTLE_DUEL_R2_ROOM_INDEX=0;if(CASTLE_DUEL_R2_ROOM_INDEX>=matches.length&&matches.length)CASTLE_DUEL_R2_SUMMARY=true;
}
function castleR2WasRevealed_(match){
  if(!match)return false;if(!castleR3ActiveStatus_(match.status))return true;
  try{return sessionStorage.getItem(castleR2RevealKey_(match))==='1';}catch(e){return false;}
}

function castleR2SwipeStyles_(){return `<style>
.castle-r2-room-scene{position:relative;overflow:hidden;border-radius:9px;padding:18px;background:#17131a;border:1px solid rgba(244,212,138,.28);box-shadow:inset 0 0 60px rgba(0,0,0,.36)}
.castle-r2-room-scene:before,.castle-r2-room-scene:after{content:"";position:absolute;pointer-events:none;z-index:0}.castle-r2-room-scene>*{position:relative;z-index:1}
.castle-r2-room-human{background:radial-gradient(circle at 18% 22%,rgba(255,186,90,.19),transparent 18%),radial-gradient(circle at 82% 25%,rgba(255,186,90,.16),transparent 16%),linear-gradient(180deg,#262028 0 58%,#17131a 58% 100%)}
.castle-r2-room-human:after{left:9%;right:9%;bottom:7%;height:24%;border-radius:50% 50% 10px 10px;background:linear-gradient(180deg,rgba(80,50,35,.92),rgba(39,24,20,.96));box-shadow:0 -8px 30px rgba(0,0,0,.4)}
.castle-r2-room-tv{background:linear-gradient(90deg,rgba(82,58,45,.72) 2px,transparent 2px) 0 0/92px 100%,radial-gradient(circle at 50% 18%,rgba(243,207,141,.18),transparent 28%),linear-gradient(180deg,#30251f,#17131a)}
.castle-r2-room-tv:after{inset:8% 7% 36%;border:2px solid rgba(218,179,98,.25);box-shadow:inset 0 0 0 8px rgba(80,52,28,.18);border-radius:10px}
.castle-r2-room-host{background:radial-gradient(circle at 50% 18%,rgba(255,215,130,.22),transparent 28%),linear-gradient(90deg,rgba(91,51,27,.18),transparent 30%,rgba(91,51,27,.18)),linear-gradient(180deg,#34251c,#17131a)}
.castle-r2-room-host:after{left:12%;right:12%;bottom:5%;height:31%;background:linear-gradient(180deg,#5a3822,#271811);clip-path:polygon(8% 0,92% 0,100% 100%,0 100%);opacity:.78}
.castle-r2-room-mask{background:radial-gradient(ellipse at 50% 28%,rgba(173,127,255,.23),transparent 25%),linear-gradient(115deg,#111016 0 28%,#2b1d35 49%,#111016 71% 100%)}
.castle-r2-room-mask:after{left:35%;right:35%;top:7%;bottom:35%;border-radius:50%;background:radial-gradient(circle,rgba(255,255,255,.12),transparent 60%);filter:blur(2px)}
.castle-r2-room-murder{background:radial-gradient(circle at 50% 22%,rgba(142,15,24,.35),transparent 24%),repeating-linear-gradient(90deg,#161014 0 34px,#211319 34px 38px)}
.castle-r2-room-murder:after{left:38%;right:38%;top:7%;bottom:7%;border:1px solid rgba(165,39,49,.45);background:linear-gradient(180deg,rgba(91,12,22,.23),rgba(0,0,0,.45));box-shadow:0 0 35px rgba(115,15,25,.4)}
.castle-r2-room-finale{background:radial-gradient(circle at 50% 15%,rgba(255,213,107,.26),transparent 23%),linear-gradient(90deg,#35151d,#17131a 28%,#17131a 72%,#35151d)}
.castle-r2-room-finale:after{left:38%;right:38%;top:12%;height:36%;background:linear-gradient(180deg,#8b6b30,#4f3519);clip-path:polygon(18% 0,82% 0,100% 100%,0 100%);opacity:.5}
.castle-r2-room-heading{text-align:center;margin:0 0 16px}.castle-r2-room-heading h2{margin:2px 0 4px;color:#f4d48a;font-size:clamp(24px,5vw,34px)}.castle-r2-room-heading p{margin:0;opacity:.78}
.castle-r2-swipe-wrap{margin-top:16px;touch-action:pan-y}.castle-r2-swipe-progress{display:flex;gap:8px;justify-content:center;align-items:center;margin:4px 0 12px}.castle-r2-swipe-progress span{width:10px;height:10px;border-radius:50%;background:rgba(255,255,255,.28)}.castle-r2-swipe-progress span.is-active{background:#f4d48a;box-shadow:0 0 0 4px rgba(244,212,138,.13)}
.castle-r2-paper{position:relative;color:#392714;border-radius:7px;padding:24px 20px 22px;background:linear-gradient(135deg,rgba(255,252,236,.97),rgba(237,219,175,.98));border:1px solid rgba(100,70,30,.42);box-shadow:0 18px 40px rgba(0,0,0,.28),inset 0 0 45px rgba(125,91,45,.09);overflow:hidden}.castle-r2-paper:before,.castle-r2-paper:after{content:"";position:absolute;left:-4%;right:-4%;height:1px;background:rgba(112,79,40,.22);transform-origin:center}.castle-r2-paper:before{top:29%;transform:rotate(7deg)}.castle-r2-paper:after{bottom:29%;transform:rotate(-7deg)}.castle-r2-paper>*{position:relative;z-index:1}
.castle-r2-script{font-family:"Apple Chancery","Segoe Script","Brush Script MT",cursive;font-size:clamp(22px,4.4vw,31px);line-height:1.06;margin:0 0 10px;color:#3c2616}.castle-r2-paper-sub{font-size:13px;letter-spacing:.11em;text-transform:uppercase;font-weight:900;color:#715534;margin-bottom:8px}
.castle-r2-check-list{display:grid;gap:6px}.castle-r2-check{display:flex;align-items:center;gap:14px;border:1px solid rgba(88,58,27,.35);border-radius:0;padding:10px 12px;background:rgba(219,199,158,.28);cursor:pointer;font-family:"Apple Chancery","Segoe Script","Brush Script MT",cursive;font-size:29px;font-weight:700}.castle-r2-check.is-selected{background:rgba(127,29,36,.11);border-color:#7d1f28;box-shadow:inset 0 0 0 2px rgba(125,31,40,.1)}.castle-r2-check input{appearance:none;-webkit-appearance:none;width:27px;height:27px;min-width:27px;border:2px solid #50371f;border-radius:4px;background:#fffdf3;display:grid;place-items:center;margin:0}.castle-r2-check input:checked{background:#7d1f28;border-color:#7d1f28}.castle-r2-check input:checked:after{content:"✓";color:#fff;font-family:Arial,sans-serif;font-size:20px;font-weight:900;line-height:1}
.castle-r2-swipe-actions{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:14px}.castle-r2-swipe-back,.castle-r2-swipe-next{min-height:50px;border-radius:13px;font-weight:900;cursor:pointer}.castle-r2-swipe-back{background:#20283a;border:1px solid rgba(255,255,255,.22);color:#fff}.castle-r2-swipe-next{border:0;background:#f4d48a;color:#281b0d}.castle-r2-swipe-next:disabled{opacity:.45;cursor:not-allowed}.castle-r2-swipe-hint{text-align:center;font-size:12px;opacity:.65;margin-top:10px}
.castle-r2-confirm-card{margin-top:16px;border-radius:18px;padding:20px;text-align:center;background:linear-gradient(145deg,#6c1d29,#3c1119);border:1px solid rgba(255,214,142,.3);box-shadow:0 15px 34px rgba(0,0,0,.32)}.castle-r2-confirm-card .castle-r2-snark{font-family:"Apple Chancery","Segoe Script","Brush Script MT",cursive;font-size:clamp(30px,6vw,44px);color:#ffe3a3;margin:2px 0 8px}.castle-r2-confirm-card p{margin:6px 0 14px;color:#f5e9de}.castle-r2-click-seal{width:100%;min-height:58px;border:1px solid rgba(255,225,168,.45);border-radius:14px;background:#8f2734;color:#fff6df;font-weight:1000;font-size:17px;letter-spacing:.06em;cursor:pointer}.castle-r2-click-seal:disabled{opacity:.55}.castle-r2-change-link{margin-top:12px;border:0;background:transparent;color:#f7dfb0;text-decoration:underline;cursor:pointer;font-weight:800}
.castle-r2-submitting{margin-top:16px;border-radius:18px;padding:22px;text-align:center;background:#20171d;border:1px solid rgba(244,212,138,.32)}.castle-r2-sealing-dot{display:inline-block;width:10px;height:10px;border-radius:50%;background:#f4d48a;margin:0 4px;animation:castleR2SealPulse .8s infinite alternate}.castle-r2-sealing-dot:nth-child(2){animation-delay:.15s}.castle-r2-sealing-dot:nth-child(3){animation-delay:.3s}@keyframes castleR2SealPulse{from{opacity:.25;transform:translateY(0)}to{opacity:1;transform:translateY(-4px)}}
.castle-r2-envelope{position:relative;margin:18px auto 6px;max-width:590px;min-height:300px;padding:68px 24px 36px;color:#392714;text-align:center;border-radius:10px;background:linear-gradient(145deg,#fff9e8,#e8d0a0);border:1px solid #b9955f;box-shadow:0 20px 45px rgba(0,0,0,.34);overflow:hidden}.castle-r2-envelope:before{content:"";position:absolute;left:-1px;right:-1px;top:-1px;height:52%;background:linear-gradient(145deg,transparent 49.5%,rgba(117,82,42,.28) 50%,transparent 50.8%),linear-gradient(215deg,transparent 49.5%,rgba(117,82,42,.28) 50%,transparent 50.8%);pointer-events:none}.castle-r2-envelope-title{font-family:"Apple Chancery","Segoe Script","Brush Script MT",cursive;font-size:42px;line-height:1;color:#4b2d18;margin-bottom:20px}.castle-r2-envelope-choice{font-family:"Apple Chancery","Segoe Script","Brush Script MT",cursive;font-size:25px;margin:9px 0}.castle-r2-wax-seal{width:78px;height:78px;border-radius:50%;margin:24px auto 10px;display:grid;place-items:center;color:#f4d7ab;background:radial-gradient(circle at 35% 28%,#c14950,#7e1722 48%,#4f0c14 100%);border:5px double rgba(70,5,11,.55);box-shadow:0 7px 15px rgba(74,11,18,.38);font-family:Georgia,serif;font-size:30px;font-weight:900}.castle-r2-hidden-note{font-size:13px;font-weight:900;letter-spacing:.04em;color:#69513a;margin-top:12px}
.castle-r3-banish{margin-top:14px;padding:12px 14px;border-radius:14px;background:rgba(113,25,34,.35);border:1px solid rgba(244,212,138,.24)}.castle-r3-banish-top{display:flex;justify-content:space-between;gap:12px;font-weight:900}.castle-r3-banish-pips{display:flex;gap:7px;margin-top:9px}.castle-r3-banish-pip{height:10px;flex:1;border-radius:99px;background:rgba(255,255,255,.14)}.castle-r3-banish-pip.is-on{background:#9d2633;box-shadow:0 0 10px rgba(157,38,51,.55)}.castle-r3-banish-note{margin:8px 0 0;font-size:12px;opacity:.75}
.castle-r3-traitor-card{margin-top:16px;border-radius:18px;padding:20px;background:linear-gradient(145deg,#351117,#171015);border:1px solid rgba(198,45,58,.48);text-align:center}.castle-r3-traitor-card h2{color:#ffbd8e;margin:6px 0}.castle-r3-traitor-list{display:grid;gap:10px;margin-top:14px;text-align:left}.castle-r3-traitor-option{display:flex;align-items:center;gap:12px;background:#f6e7c6;color:#3d2117;border:2px solid transparent;border-radius:13px;padding:12px 14px;cursor:pointer;font-weight:900}.castle-r3-traitor-option.is-selected{border-color:#9c2430;background:#fff4da}.castle-r3-traitor-option span:first-child{width:24px;height:24px;border:2px solid #5d3c27;border-radius:5px;display:grid;place-items:center}.castle-r3-traitor-option.is-selected span:first-child{background:#8d1d29;color:#fff;border-color:#8d1d29}.castle-r3-full{width:100%;margin-top:14px}
.castle-r3-fate-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:14px}.castle-r3-fate-card{min-height:180px;border-radius:17px;border:1px solid #c8a46d;background:linear-gradient(150deg,#f7e7bf,#c9a56c);color:#4a2f1b;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;cursor:pointer;box-shadow:0 14px 28px rgba(0,0,0,.28);font-family:"Apple Chancery","Segoe Script",cursive;font-size:28px;font-weight:900}.castle-r3-fate-seal{width:58px;height:58px;border-radius:50%;display:grid;place-items:center;background:#791722;color:#f0c88b;border:4px double #4d0b12;font-family:Georgia,serif}.castle-r3-fate-result{margin-top:16px;border-radius:18px;padding:22px;text-align:center}.castle-r3-fate-safe{background:#dff2e3;color:#18391f}.castle-r3-fate-dead{background:#5e1720;color:#fff3df}.castle-r3-fate-result h2{margin:2px 0 7px;font-size:32px}
.castle-r3-host-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:11px;margin-top:15px}.castle-r3-host-envelope{min-height:150px;border:1px solid #c8a46d;border-radius:14px;background:linear-gradient(145deg,#fff1ce,#d9b879);color:#4d301a;font-weight:1000;cursor:pointer;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:11px}.castle-r3-host-envelope .castle-r3-fate-seal{width:52px;height:52px}
.castle-r3-mask-outcome{margin-top:16px;border-radius:18px;padding:18px;background:rgba(0,0,0,.34);border:1px solid rgba(244,212,138,.3)}.castle-r3-mask-outcome h2{color:#f4d48a}
@media(max-width:560px){.castle-r2-room-scene{padding:12px}.castle-r2-paper{padding:14px 12px}.castle-r2-check{font-size:20px;padding:9px 11px;gap:9px}.castle-r2-swipe-actions{grid-template-columns:1fr}.castle-r2-envelope{min-height:270px;padding-left:15px;padding-right:15px}.castle-r2-envelope-title{font-size:36px}.castle-r3-host-grid{grid-template-columns:1fr}.castle-r3-fate-card{min-height:145px}}
</style>`;}

function castleR3BanishHtml_(s){
  var p=s.player||{},threshold=Number(s.config&&s.config.banishThreshold||5),banish=Math.max(0,Number(p.banish||0));
  var pips='';for(var i=0;i<threshold;i++)pips+=`<span class="castle-r3-banish-pip${i<banish?' is-on':''}"></span>`;
  return `<div class="castle-r3-banish"><div class="castle-r3-banish-top"><span>BANISH PRESSURE</span><span>${banish} / ${threshold}</span></div><div class="castle-r3-banish-pips">${pips}</div><p class="castle-r3-banish-note">Wrong reads add Banish. Survive the episode and one Banish is removed. Reach the limit and one life is lost.</p></div>`;
}
function castleR2HeaderHtml_(s){
  var p=s.player||{};
  return `<section class="castle-r2-hero"><div class="castle-r2-kicker">THE TRAITORS · CASTLE DUEL</div><h1>Enter the Castle</h1><p>One room at a time. Read your opponent. Choose who to trust.</p><div class="castle-r2-meta"><span>Jackpot: ${castleEscape_(s.config&&s.config.jackpot||0)} pts</span><span>Lives: ${castleEscape_(p.lives)} · Secret shields: ${castleEscape_(p.shield)}</span></div>${castleR3BanishHtml_(s)}</section>`;
}
function castleR2AnnouncementHtml_(s){
  var out='';
  if(s&&s.announcement&&Array.isArray(s.announcement.events)&&s.announcement.events.length){
    out+=`<section class="castle-r2-stage castle-r2-hero"><div class="castle-r2-kicker">Previous Castle Reveal · Episode ${castleEscape_(s.announcement.episode)}</div>${s.announcement.events.map(function(e){
      var banish=String(e.source||'').indexOf('BANISH')===0;
      var text=banish?(e.lost?'reached the Banish limit and lost 1 life.':'reached the Banish limit.'):(e.source==='ABSENCE'?'missed the episode and lost 1 life.':e.lost?'was murdered and lost 1 life.':'was targeted, but a Secret Shield saved them.');
      return `<p><b>${castleEscape_(e.victim)}</b> ${text}${e.source==='HUMAN'||e.source==='BOTH'?' The human murderer remains secret until the finale.':''}</p>`;
    }).join('')}</section>`;
  }
  if(s&&s.privateNotice){
    var n=s.privateNotice,banish=String(n.source||'').indexOf('BANISH')===0;
    out+=`<section class="castle-r2-stage"><div class="castle-r2-lock-warning"><b>${banish?'Banish limit reached':n.source==='ABSENCE'?'Missed Castle episode':n.shieldUsed?'Your Secret Shield saved you!':'You have been murdered!'}</b><br>${banish?'The Castle took one life because your Banish pressure reached the episode limit. ':n.source==='HUMAN'||n.source==='BOTH'?'One of your fellow PATTC players targeted you. ':''}${n.lost?'You lost one life.':n.shieldUsed?'Your shield was used. No life was lost.':''}</div></section>`;
  }
  return out;
}
function castleR2SwipePanel_(m){return Number(CASTLE_DUEL_R2_SWIPE_PANELS[m.id]||0)===1?1:0;}
function castleR2SwipeSetPanel_(id,panel){
  var m=(CASTLE_DUEL_STATE.matches||[]).find(function(x){return x.id===id;});if(!m)return;panel=panel===1?1:0;var draft=castleR2Draft_(m);
  if(panel===1&&!draft.guess){if(typeof castleNotify_==='function')castleNotify_('Choose what you think your opponent will do first.',true);return;}
  CASTLE_DUEL_R2_SWIPE_PANELS[id]=panel;CASTLE_DUEL_R2_CONFIRMING[id]=false;castleR2Render_();
}
function castleR2SwipeSelect_(id,field,value){var m=(CASTLE_DUEL_STATE.matches||[]).find(function(x){return x.id===id;});if(!m)return;var draft=castleR2Draft_(m);draft[field]=value;CASTLE_DUEL_R2_CONFIRMING[id]=false;castleR2Render_();}
function castleR2SwipeChoice_(m,field,value,label){var draft=castleR2Draft_(m),selected=draft[field]===value;return `<label class="castle-r2-check${selected?' is-selected':''}"><input type="checkbox" ${selected?'checked':''} onchange="castleR2SwipeSelect_('${castleEscape_(m.id)}','${field}','${value}')"><span>${castleEscape_(label)}</span></label>`;}
function castleR2SwipeTouchStart_(event,id){var t=event&&event.touches&&event.touches[0];if(t)CASTLE_DUEL_R2_TOUCH={id:id,x:t.clientX,y:t.clientY};}
function castleR2SwipeTouchEnd_(event,id){var start=CASTLE_DUEL_R2_TOUCH,t=event&&event.changedTouches&&event.changedTouches[0];CASTLE_DUEL_R2_TOUCH=null;if(!start||start.id!==id||!t)return;var dx=t.clientX-start.x,dy=t.clientY-start.y;if(Math.abs(dx)<55||Math.abs(dx)<Math.abs(dy))return;var m=(CASTLE_DUEL_STATE.matches||[]).find(function(x){return x.id===id;});if(!m)return;var panel=castleR2SwipePanel_(m);if(dx<0&&panel===0)castleR2SwipeSetPanel_(id,1);if(dx>0&&panel===1)castleR2SwipeSetPanel_(id,0);}
function castleR2SwipeSnarkKey_(m){var user=CASTLE_DUEL_STATE&&CASTLE_DUEL_STATE.player?CASTLE_DUEL_STATE.player.user:'';return 'pattcCastleSnarkR2:'+String(user||'')+':'+String(CASTLE_DUEL_R2_ROUND_KEY||'')+':'+String(m&&m.id||'');}
function castleR2SwipeSnark_(m){
  var lines=['Are You Sure?','Seems Good to Me...',"That Wasn't That Difficult, Was It?",'Nice Choice... Maybe.','Bold Move. Probably.',"Trust Your Gut. Or Don't.",'Interesting... Very Interesting.','The Castle Is Watching.','Feeling Confident?','No Turning Back... Almost.','Well... You Picked Something.','Courageous. Or Suspicious.','Would You Bet a Life on That?','The Walls Have Ears.','Your Opponent Would Love to Know That.'];
  var key=castleR2SwipeSnarkKey_(m),prior='';try{prior=sessionStorage.getItem(key)||'';}catch(e){}if(prior)return prior;
  var used={};try{(CASTLE_DUEL_STATE.matches||[]).forEach(function(x){var value=sessionStorage.getItem(castleR2SwipeSnarkKey_(x))||'';if(value)used[value]=true;});}catch(e){}
  var available=lines.filter(function(line){return !used[line];});if(!available.length)available=lines.slice();var pick=available[Math.floor(Math.random()*available.length)];try{sessionStorage.setItem(key,pick);}catch(e){}return pick;
}
function castleR2SwipeBeginConfirm_(id){var m=(CASTLE_DUEL_STATE.matches||[]).find(function(x){return x.id===id;});if(!m)return;var draft=castleR2Draft_(m);if(!draft.guess||!draft.choice){if(typeof castleNotify_==='function')castleNotify_('Choose both your prediction and your decision.',true);return;}castleR2SwipeSnark_(m);CASTLE_DUEL_R2_CONFIRMING[id]=true;castleR2Render_();}
function castleR2SwipeCancelConfirm_(id){CASTLE_DUEL_R2_CONFIRMING[id]=false;castleR2Render_();}
async function castleR2SwipeSeal_(id){
  if(CASTLE_DUEL_R2_SUBMITTING[id])return;var m=(CASTLE_DUEL_STATE.matches||[]).find(function(x){return x.id===id;});if(!m)return;var draft=castleR2Draft_(m);if(!draft.guess||!draft.choice)return;
  CASTLE_DUEL_R2_SUBMITTING[id]=true;castleR2Render_();
  try{
    if(m.kind==='MASK'&&m.outcome==='FAITHFUL')await castleCall_('castleDuelMaskedAccept',{roundKey:CASTLE_DUEL_STATE.round.key,matchId:id,step:'FAITHFUL_DUEL',guess:draft.guess,choice:draft.choice});
    else await castleCall_('castleDuelSubmit',{roundKey:CASTLE_DUEL_STATE.round.key,matchId:id,guess:draft.guess,choice:draft.choice});
    CASTLE_DUEL_R2_CONFIRMING[id]=false;await castleR2ReloadState_();
  }catch(e){CASTLE_DUEL_R2_SUBMITTING[id]=false;castleR2Render_();if(typeof castleNotify_==='function')castleNotify_(e.message||'Could not seal your decision.',true);}finally{CASTLE_DUEL_R2_SUBMITTING[id]=false;}
}
function castleR2RoomTheme_(m,round){
  if(round&&round.finale)return {cls:'castle-r2-room-finale',title:'The Throne Room',sub:'Ten final tests. Every choice echoes.'};
  if(m.traitorStage||m.status==='FATE_REQUIRED')return {cls:'castle-r2-room-murder',title:'The Traitor Passage',sub:'Someone in the shadows has chosen you.'};
  if(m.kind==='HUMAN')return {cls:'castle-r2-room-human',title:'The Strategy Chamber',sub:'Across the table sits another PATTC player.'};
  if(m.kind==='HOST')return {cls:'castle-r2-room-host',title:"The Host's Study",sub:'A quieter room. That does not mean a safer one.'};
  if(m.kind==='MASK'&&m.outcome==='MURDERER')return {cls:'castle-r2-room-murder',title:'The Hidden Passage',sub:'Some doors in the Castle should stay closed.'};
  if(m.kind==='MASK')return {cls:'castle-r2-room-mask',title:'The Masked Hall',sub:'The face is hidden. The risk is not.'};
  return {cls:'castle-r2-room-tv',title:'The Portrait Gallery',sub:'A familiar face waits beneath the frames.'};
}
function castleR2SwipePaper_(m){
  var panel=castleR2SwipePanel_(m),draft=castleR2Draft_(m),name=castleR2OpponentName_(m),dots=`<div class="castle-r2-swipe-progress"><span class="is-active"></span><span class="${panel===1?'is-active':''}"></span></div>`;
  if(panel===0)return `<div class="castle-r2-swipe-wrap" ontouchstart="castleR2SwipeTouchStart_(event,'${castleEscape_(m.id)}')" ontouchend="castleR2SwipeTouchEnd_(event,'${castleEscape_(m.id)}')">${dots}<div class="castle-r2-paper"><div class="castle-r2-paper-sub">Secret Note I · Read Them</div><div class="castle-r2-script">What do you think ${castleEscape_(name)} will do?</div><div class="castle-r2-check-list">${castleR2SwipeChoice_(m,'guess','COOPERATE','Cooperate')}${castleR2SwipeChoice_(m,'guess','BETRAY','Betray')}</div></div><div class="castle-r2-swipe-actions"><span></span><button class="castle-r2-swipe-next" ${draft.guess?'':'disabled'} onclick="castleR2SwipeSetPanel_('${castleEscape_(m.id)}',1)">NEXT →</button></div><div class="castle-r2-swipe-hint">Swipe left or tap NEXT</div></div>`;
  return `<div class="castle-r2-swipe-wrap" ontouchstart="castleR2SwipeTouchStart_(event,'${castleEscape_(m.id)}')" ontouchend="castleR2SwipeTouchEnd_(event,'${castleEscape_(m.id)}')">${dots}<div class="castle-r2-paper"><div class="castle-r2-paper-sub">Secret Note II · Your Move</div><div class="castle-r2-script">What will YOU do?</div><div class="castle-r2-check-list">${castleR2SwipeChoice_(m,'choice','COOPERATE','Cooperate')}${castleR2SwipeChoice_(m,'choice','BETRAY','Betray')}</div></div><div class="castle-r2-swipe-actions"><button class="castle-r2-swipe-back" onclick="castleR2SwipeSetPanel_('${castleEscape_(m.id)}',0)">← BACK</button><button class="castle-r2-swipe-next" ${draft.choice?'':'disabled'} onclick="castleR2SwipeBeginConfirm_('${castleEscape_(m.id)}')">LOCK IN DECISION</button></div><div class="castle-r2-swipe-hint">Swipe right to review your prediction</div></div>`;
}
function castleR2SwipeConfirmHtml_(m){var draft=castleR2Draft_(m);if(CASTLE_DUEL_R2_SUBMITTING[m.id])return `<div class="castle-r2-submitting"><div class="castle-r2-kicker">THE CASTLE IS RECORDING YOUR CHOICE</div><h2>SEALING YOUR DECISION...</h2><div><span class="castle-r2-sealing-dot"></span><span class="castle-r2-sealing-dot"></span><span class="castle-r2-sealing-dot"></span></div><p>Your choices are being locked. Please do not tap again.</p></div>`;return `<div class="castle-r2-confirm-card"><div class="castle-r2-snark">${castleEscape_(castleR2SwipeSnark_(m))}</div><p>Prediction: <b>${castleEscape_(draft.guess)}</b> · Your move: <b>${castleEscape_(draft.choice)}</b></p><button class="castle-r2-click-seal" onclick="castleR2SwipeSeal_('${castleEscape_(m.id)}')">CLICK TO SEAL IT</button><br><button class="castle-r2-change-link" onclick="castleR2SwipeCancelConfirm_('${castleEscape_(m.id)}')">Change my choices</button></div>`;}
function castleR2SwipeEnvelope_(m,index,matches,settled){
  var title=settled?'DECISION REVEALED':'DECISION SEALED',body=`<div class="castle-r2-envelope"><div class="castle-r2-envelope-title">${title}</div><div class="castle-r2-envelope-choice">Your Prediction: <b>${castleEscape_(m.guess||'—')}</b></div><div class="castle-r2-envelope-choice">Your Decision: <b>${castleEscape_(m.choice||'—')}</b></div>`;
  if(settled){body+=`<div class="castle-r2-envelope-choice">Opponent Decision: <b>${castleEscape_(m.answer||'—')}</b></div><div class="castle-r2-envelope-choice">Result: <b>${Number(m.points||0)>=0?'+':''}${castleEscape_(m.points||0)} pts</b></div>${m.banishAdded?'<div class="castle-r2-envelope-choice">You were duped · <b>+1 Banish</b></div>':''}`;}
  body+=`<div class="castle-r2-wax-seal">C</div><div class="castle-r2-hidden-note">${settled?'The Castle has opened the record.':'Your opponent\'s decision stays hidden until settlement.'}</div></div>`;return body+castleR2NextButton_(index,matches);
}
function castleR3TraitorPick_(id,traitorId){CASTLE_DUEL_R3_TRAITOR_GUESSES[id]=traitorId;castleR2Render_();}
async function castleR3SubmitTraitor_(id){
  var pick=CASTLE_DUEL_R3_TRAITOR_GUESSES[id];if(!pick){castleNotify_('Choose which Traitor you think is after you.',true);return;}
  try{await castleCall_('castleDuelSubmit',{roundKey:CASTLE_DUEL_STATE.round.key,matchId:id,step:'TRAITOR_IDENTITY',traitorId:pick});await castleR2ReloadState_();}catch(e){castleNotify_(e.message||'Could not lock your Traitor guess.',true);}
}
function castleR3TraitorIdentityHtml_(m){
  var candidates=m.traitorCandidates||[],pick=CASTLE_DUEL_R3_TRAITOR_GUESSES[m.id]||'';
  return `<div class="castle-r3-traitor-card"><div class="castle-r2-kicker">A TRAITOR IS AFTER YOU</div><h2>Who is hiding in the passage?</h2><p>Name the correct Traitor and you are safe from murder in this encounter. Then you still have to read their Cooperate/Betray move.</p><div class="castle-r3-traitor-list">${candidates.map(function(t){var sel=String(pick)===String(t.id);return `<button type="button" class="castle-r3-traitor-option${sel?' is-selected':''}" onclick="castleR3TraitorPick_('${castleEscape_(m.id)}','${castleEscape_(t.id)}')"><span>${sel?'✓':''}</span><span>${castleEscape_(t.name)}</span></button>`;}).join('')}</div><button class="castle-r2-primary castle-r3-full" ${pick?'':'disabled'} onclick="castleR3SubmitTraitor_('${castleEscape_(m.id)}')">LOCK IN TRAITOR</button></div>`;
}
async function castleR3ChooseFate_(id,slot,masked){try{var action=masked?'castleDuelMaskedAccept':'castleDuelSubmit',payload={roundKey:CASTLE_DUEL_STATE.round.key,matchId:id};if(masked){payload.step='FATE';payload.fateSlot=slot;}else{payload.step='TRAITOR_FATE';payload.fateSlot=slot;}await castleCall_(action,payload);await castleR2ReloadState_();}catch(e){castleNotify_(e.message||'The fate card could not be opened.',true);}}
function castleR3FateChoiceHtml_(m,masked){
  return `<div class="castle-r3-traitor-card"><div class="castle-r2-kicker">${masked?'TRAITOR CARD':'WRONG TRAITOR'}</div><h2>${masked?castleEscape_(m.opponent||'A Traitor'):'You accused the wrong Traitor.'}</h2><p>${masked?'A Traitor has found you.':'The real Traitor stays hidden.'} Choose one sealed Fate Card. One lets you escape. One carries a murder attempt.</p><div class="castle-r3-fate-grid"><button class="castle-r3-fate-card" onclick="castleR3ChooseFate_('${castleEscape_(m.id)}',1,${masked?'true':'false'})"><span class="castle-r3-fate-seal">I</span>FATE CARD I</button><button class="castle-r3-fate-card" onclick="castleR3ChooseFate_('${castleEscape_(m.id)}',2,${masked?'true':'false'})"><span class="castle-r3-fate-seal">II</span>FATE CARD II</button></div></div>`;
}
function castleR3FateResultHtml_(m,index,matches){
  var safe=m.fateResult==='SAFE',shield=CASTLE_DUEL_STATE&&CASTLE_DUEL_STATE.player&&Number(CASTLE_DUEL_STATE.player.shield||0)>0;
  return `<div class="castle-r3-fate-result ${safe?'castle-r3-fate-safe':'castle-r3-fate-dead'}"><div class="castle-r2-kicker">FATE REVEALED</div><h2>${safe?'NOT MURDERED':'MURDERED'}</h2><p>${safe?'You escaped the Traitor this time.':shield?'A murder attempt is sealed. Your current Secret Shield will protect you when the episode settles.':'A murder attempt is sealed. One life is at risk when the episode settles.'}</p></div>${castleR2NextButton_(index,matches)}`;
}
async function castleR3ChooseHost_(id,slot){try{await castleCall_('castleDuelMaskedAccept',{roundKey:CASTLE_DUEL_STATE.round.key,matchId:id,step:'HOST',hostSlot:slot});await castleR2ReloadState_();}catch(e){castleNotify_(e.message||'The Host envelope could not be opened.',true);}}
function castleR3HostChoiceHtml_(m){return `<div class="castle-r3-mask-outcome"><div class="castle-r2-kicker">HOST CARD</div><h2>The Host offers three sealed envelopes.</h2><p>Choose one. Gold pays points, Protection can restore a life or add a shield, and Mercy clears your Banish pressure. You will not know which is which until you open it.</p><div class="castle-r3-host-grid">${[1,2,3].map(function(i){return `<button class="castle-r3-host-envelope" onclick="castleR3ChooseHost_('${castleEscape_(m.id)}',${i})"><span class="castle-r3-fate-seal">${i}</span>SEALED ENVELOPE</button>`;}).join('')}</div></div>`;}
function castleR3HostResultHtml_(m,index,matches){var reward=m.hostReward||'',copy=reward==='GOLD'?'Gold — your wager becomes bonus points.':reward==='PROTECTION'?'Protection — the Host restored a life or granted a Secret Shield.':reward==='MERCY'?'Mercy — your Banish pressure has been cleared.':'The Host has made a choice.';return `<div class="castle-r3-mask-outcome"><div class="castle-r2-kicker">HOST ENVELOPE OPENED</div><h2>${castleEscape_(reward||'REWARD')}</h2><p>${castleEscape_(copy)}</p></div>${castleR2NextButton_(index,matches)}`;}
function castleR2NormalControls_(m,index,matches,round){
  var locked=castleR2RoundLocked_(round);if(m.status==='IDENTIFY_REQUIRED')return locked?'<div class="castle-r2-lock-warning">ROUND LOCKED · The Traitor escaped unidentified.</div>':castleR3TraitorIdentityHtml_(m);
  if(m.status==='FATE_REQUIRED')return locked?'<div class="castle-r2-lock-warning">ROUND LOCKED · Your Fate Card was not chosen.</div>':castleR3FateChoiceHtml_(m,false);
  if(m.status==='OPEN'){if(locked)return `<div class="castle-r2-lock-warning">ROUND LOCKED · No additional decisions can be submitted.</div>`;if(CASTLE_DUEL_R2_CONFIRMING[m.id]||CASTLE_DUEL_R2_SUBMITTING[m.id])return castleR2SwipeConfirmHtml_(m);return castleR2SwipePaper_(m);}
  if(m.status==='LOCKED'&&m.fateResult)return castleR3FateResultHtml_(m,index,matches);
  if(m.status==='LOCKED')return castleR2SwipeEnvelope_(m,index,matches,false);
  if(m.status==='SETTLED'&&m.fateResult)return castleR3FateResultHtml_(m,index,matches);
  if(m.status==='SETTLED')return castleR2SwipeEnvelope_(m,index,matches,true);return '';
}
async function castleR2Mask_(id,accept){try{if(accept&&!window.confirm('Accept this wager and reveal a Masked Hall card?'))return;await castleCall_('castleDuelMaskedAccept',{roundKey:CASTLE_DUEL_STATE.round.key,matchId:id,accept:accept});await castleR2ReloadState_();}catch(e){castleNotify_(e.message,true);}}
function castleR2MaskControls_(m,index,matches,round,players){
  var locked=castleR2RoundLocked_(round);
  if(m.status==='OPEN'){if(locked)return `<div class="castle-r2-lock-warning">ROUND LOCKED · This Masked encounter expired.</div>`;return `<div class="castle-r2-mask-card"><div class="castle-r2-kicker">MASKED WAGER</div><div class="castle-r2-wager">${castleEscape_(m.wager)} pts</div><p>Accept to draw one Castle card: Faithful, Traitor, Host, or Murderer. Half of an accepted wager is added separately to the Castle jackpot.</p><div class="castle-r2-actions"><button class="castle-r2-primary" onclick="castleR2Mask_('${castleEscape_(m.id)}',true)">ACCEPT & DRAW CARD</button><button class="castle-r2-secondary" onclick="castleR2Mask_('${castleEscape_(m.id)}',false)">DECLINE</button></div></div>`;}
  if(m.status==='FATE_REQUIRED'&&m.outcome==='TRAITOR')return locked?'<div class="castle-r2-lock-warning">ROUND LOCKED · Fate was not chosen.</div>':castleR3FateChoiceHtml_(m,true);
  if(m.status==='HOST_REQUIRED'&&m.outcome==='HOST')return locked?'<div class="castle-r2-lock-warning">ROUND LOCKED · The Host envelopes closed.</div>':castleR3HostChoiceHtml_(m);
  if(m.status==='MASK_DUEL_REQUIRED'&&m.outcome==='FAITHFUL'){if(locked)return '<div class="castle-r2-lock-warning">ROUND LOCKED · The Faithful duel expired.</div>';if(CASTLE_DUEL_R2_CONFIRMING[m.id]||CASTLE_DUEL_R2_SUBMITTING[m.id])return castleR2SwipeConfirmHtml_(m);return `<div class="castle-r3-mask-outcome"><div class="castle-r2-kicker">FAITHFUL CARD · ${castleEscape_(m.opponent||'Faithful')}</div><p>Read the Faithful correctly to earn points and recover your wager. Get duped and you score 0 and gain +1 Banish.</p></div>${castleR2SwipePaper_(m)}`;}
  if(m.status==='TARGET_REQUIRED'){
    var targets=(players||[]).filter(function(x){return x.user!==CASTLE_DUEL_STATE.player.user&&x.lives>0;});
    return `<div class="castle-r2-mask-card castle-r2-danger"><div class="castle-r2-kicker">MURDERER CARD</div><h2>YOU HAVE THE POWER</h2><p>Choose an active PATTC player now. Your identity remains secret until the finale.</p><select id="castleR2Target-${castleEscape_(m.id)}" class="castle-r2-target">${targets.map(function(x){return `<option value="${castleEscape_(x.user)}">${castleEscape_(x.user)}</option>`;}).join('')}</select><button class="castle-r2-primary" onclick="castleR2Target_('${castleEscape_(m.id)}')">CONFIRM SECRET TARGET</button></div>`;
  }
  if(m.status==='DECLINED')return `<div class="castle-r2-sealed"><h2>Wager Declined</h2><p>No wager was charged. No jackpot contribution was made.</p></div>${castleR2NextButton_(index,matches)}`;
  if(m.status==='LOCKED'&&m.outcome==='TRAITOR'&&m.fateResult)return castleR3FateResultHtml_(m,index,matches);
  if(m.status==='LOCKED'&&m.outcome==='HOST')return castleR3HostResultHtml_(m,index,matches);
  if(m.status==='LOCKED'&&m.outcome==='FAITHFUL')return castleR2SwipeEnvelope_(m,index,matches,false);
  if(m.status==='LOCKED'&&m.outcome==='MURDERER')return `<div class="castle-r3-mask-outcome"><div class="castle-r2-kicker">MURDERER CARD SEALED</div><h2>Your target has been chosen.</h2><p>The Castle will keep your identity secret until the finale.</p></div>${castleR2NextButton_(index,matches)}`;
  if(m.status==='SETTLED')return `<div class="castle-r3-mask-outcome"><div class="castle-r2-kicker">MASKED HALL RESULT</div><h2>${castleEscape_(m.outcome||'Masked Encounter')}</h2><p>You earned <b>${castleEscape_(m.points||0)} points</b>.${m.banishAdded?' You were duped and gained <b>+1 Banish</b>.':''}</p></div>${castleR2NextButton_(index,matches)}`;
  return '';
}
function castleR2RoomHtml_(s,index){
  var matches=s.matches||[],m=matches[index],round=s.round,players=s.leaderboard||[];if(!m)return castleR2SummaryHtml_(s);if(!castleR2WasRevealed_(m)&&!castleR2RoundLocked_(round))return castleR2SwipeStyles_()+castleR2SpinnerHtml_(m,index,matches);
  var title=castleR2OpponentName_(m),theme=castleR2RoomTheme_(m,round),kindLabel=m.traitorStage?'TRAITOR ENCOUNTER':m.kind==='HUMAN'?'PATTC PLAYER':m.kind==='MASK'?'MASKED ENCOUNTER':m.kind==='HOST'?'SPECIAL ENCOUNTER':'TV CONTESTANT';
  return castleR2SwipeStyles_()+`<section class="castle-r2-stage">${castleR2ProgressHtml_(matches,index)}<div class="castle-r2-room-scene ${theme.cls}"><div class="castle-r2-room-heading"><div class="castle-r2-kicker">EPISODE ${castleEscape_(round&&round.number||'')} · ENCOUNTER ${index+1}</div><h2>${castleEscape_(theme.title)}</h2><p>${castleEscape_(theme.sub)}</p></div><div class="castle-r2-room"><div class="castle-r2-portrait-wrap">${castleR2Portrait_(m,false)}${m.allied?'<div class="castle-r2-ally">CASTLE FIVE ALLY</div>':''}</div><div class="castle-r2-kicker">${kindLabel}</div><h2 class="castle-r2-opponent">${castleEscape_(title)}</h2>${m.identityCorrect===true?'<p class="castle-r2-sub"><b>Correct.</b> You identified the Traitor and are safe from murder in this encounter.</p>':''}${m.identityCorrect===false&&m.status==='FATE_REQUIRED'?'<p class="castle-r2-sub"><b>Wrong Traitor.</b> The real identity remains hidden.</p>':''}${m.allied?'<p class="castle-r2-sub">One of your chosen Castle Five has appeared.</p>':''}${m.clue?`<div class="castle-r2-insight"><b>ALLIANCE INSIGHT</b><br>Your ally suggests <b>${castleEscape_(m.clue)}</b>. This clue is 75% accurate. A correct read earns the Alliance bonus.</div>`:''}${castleR2HistoryHtml_(m)}${m.kind==='MASK'?castleR2MaskControls_(m,index,matches,round,players):castleR2NormalControls_(m,index,matches,round)}</div></div></section>`;
}
