/* PATTC Football Test Lab R1 — preview-only, admin-only. */
(function(root){
  "use strict";
  var STATES={
    survivor:["real","preview","open","selected","finalized","locked","live","final-win","final-loss","eliminated","winner"],
    confidence:["real","preview","open","selected","locked","live","final-win","final-loss"],
    "team-fantasy":["real","preview","incomplete","lineup-set","locked","live","final-win","final-loss"],
    koth:["real","preview","safe","warning","strike","eliminated","champion"],
    wager:["real","preview","open","selected","locked","live","won","lost","push"]
  };
  var LABELS={real:"REAL DATA",preview:"PREVIEW / UPCOMING",open:"OPEN",selected:"SELECTED / SAVED",finalized:"FINALIZED PICK",locked:"LOCKED",live:"LIVE","final-win":"FINAL — WIN / SURVIVED","final-loss":"FINAL — LOSS","lineup-set":"LINEUP SET",incomplete:"INCOMPLETE LINEUP",safe:"SAFE",warning:"WARNING ZONE",strike:"STRIKE RECEIVED",eliminated:"ELIMINATED",winner:"WINNER",champion:"LAST MAN STANDING",won:"FINAL — WON",lost:"FINAL — LOST",push:"FINAL — PUSH"};
  var S={page:"",type:"",gameId:"",app:null,baseline:"",state:"real",week:1,panel:false};
  function txt(v){return String(v===undefined||v===null?"":v);}
  function esc(v){return txt(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");}
  function admin(){try{var s=typeof getSession==="function"?(getSession()||{}):{};var v=s.isAdmin!==undefined?s.isAdmin:(s.user&&s.user.isAdmin);return v===true||v===1||["true","yes","admin"].indexOf(txt(v).toLowerCase())!==-1;}catch(e){return false;}}
  function gid(){try{return typeof getFrontendGameId==="function"?txt(getFrontendGameId()):txt(root.APP_STATE&&root.APP_STATE.gameId);}catch(e){return "";}}
  function type(page,app){
    if(page==="survivor"){var p={};try{p=typeof SURVIVOR_PAGE_STATE!=="undefined"?(SURVIVOR_PAGE_STATE.payload||{}):{};}catch(e){} if(p.passiveKoth===true||p.mode==="king-of-the-hill"||app.querySelector(".sports-default-koth,.sports-default-koth-final"))return"koth";return app.querySelector(".survivor-page,.survivor-recovery-r3")?"survivor":"";}
    if(page==="picks"){var c=false;try{c=typeof PICKS_PAGE_DATA!=="undefined"&&PICKS_PAGE_DATA.isConfidenceGame===true;}catch(e){} return c||app.querySelector(".confidence-game-row")?"confidence":"";}
    if(page==="team-fantasy")return app.querySelector(".tf-slot,.sports-team-fantasy")?"team-fantasy":"";
    if(page==="betting")return app.querySelector(".betting-nominee-card,.betting-page,[class*='wager']")?"wager":"";
    return"";
  }
  function currentWeek(){try{if(S.type==="survivor"||S.type==="koth"){var p=SURVIVOR_PAGE_STATE.payload||{};return Number(p.currentRound&&(p.currentRound.week||p.currentRound.round)||p.week||1)||1;}if(S.type==="team-fantasy")return Number(root.TEAM_FANTASY_STATE&&root.TEAM_FANTASY_STATE.week||1)||1;if(S.type==="confidence"){var a=PICKS_PAGE_DATA.categories||[];for(var i=0;i<a.length;i++){var w=Number(a[i].week||a[i].weekNumber||a[i].sportsWeek||0);if(w>0)return w;}}}catch(e){}return 1;}
  function key(){return"pattcFootballTestLab:r1:"+encodeURIComponent(S.type+"|"+S.gameId);}
  function load(){var d={state:"real",week:currentWeek()};try{var x=JSON.parse(sessionStorage.getItem(key())||"null");if(x){d.state=x.state||d.state;d.week=Number(x.week||d.week)||d.week;}}catch(e){}if((STATES[S.type]||[]).indexOf(d.state)===-1)d.state="real";S.state=d.state;S.week=Math.max(1,Math.min(18,d.week));}
  function save(){try{sessionStorage.setItem(key(),JSON.stringify({state:S.state,week:S.week}));}catch(e){}}
  function restore(){if(!S.app)return;S.app.inert=false;document.body.classList.remove("pattc-testlab-simulating");if(S.baseline)S.app.innerHTML=S.baseline;}
  function stamp(n,l,t){if(!n)return;var x=document.createElement("div");x.className="pattc-testlab-stamp pattc-testlab-generated is-"+(t||"info");x.textContent=l;n.prepend(x);}
  function set(n,v){if(n)n.textContent=v;}
  function banner(){S.app.insertAdjacentHTML("afterbegin",'<div class="pattc-testlab-banner pattc-testlab-generated"><strong>TEST LAB — '+esc(LABELS[S.state]||S.state.toUpperCase())+'</strong><span>WEEK '+S.week+' · DISPLAY ONLY · NO SAVES</span></div>');}
  function weekLabels(){S.app.querySelectorAll(".survivor-r3-browser-head>span,.tf-week-title,.tf-week-label,.confidence-week-label,.sports-default-koth-weekbar>span:not(.is-live)").forEach(function(n){if(/week/i.test(n.textContent||"")||n.matches(".survivor-r3-browser-head>span"))n.textContent="WEEK "+S.week;});}
  function score(card,label,a,h){if(!card)return;var n=document.createElement("div");n.className="pattc-testlab-scorebar pattc-testlab-generated";n.innerHTML="<strong>"+esc(label)+"</strong><span>"+a+" — "+h+"</span>";card.appendChild(n);}
  function survivor(){weekLabels();var cards=Array.from(S.app.querySelectorAll(".survivor-r3-matchup,.survivor-final-matchup")),first=cards[0],status=first&&first.querySelector(".survivor-r2-matchup-meta strong"),hero=S.app.querySelector(".survivor-rich-hero-status"),hs=hero&&hero.querySelector("span"),hd=hero&&hero.querySelector("strong"),pick=S.app.querySelector(".survivor-r3-pick-head small");if(["selected","finalized","locked","live","final-win","final-loss","eliminated","winner"].indexOf(S.state)!==-1){var team=S.app.querySelector(".survivor-r3-team-side,.survivor-r2-team-side");if(team){team.classList.add("pattc-testlab-selected");stamp(team,"YOUR PICK","selected");}}if(S.state==="locked"){set(status,"LOCKED");set(pick,"LOCKED IN");}if(S.state==="live"){set(status,"LIVE · Q2 06:42");set(pick,"LOCKED IN · LIVE");score(first,"LIVE · Q2 06:42","17","14");}if(S.state==="final-win"){set(status,"FINAL");set(hs,"STILL ALIVE");set(hd,"Week survived · streak continues");score(first,"FINAL · SURVIVED","24","20");}if(S.state==="final-loss"){set(status,"FINAL");set(hs,"LOSS — LIFE USED");set(hd,"One life consumed · streak reset");score(first,"FINAL · LOSS","17","27");}if(S.state==="eliminated"){set(hs,"ELIMINATED");set(hd,"Season complete");}if(S.state==="winner"){set(hs,"WINNER");set(hd,"LAST SURVIVOR STANDING");}if(["preview","open","selected","finalized"].indexOf(S.state)!==-1){set(status,"SCHEDULED");set(pick,S.state==="finalized"?"FINALIZED · OPEN UNTIL KICKOFF":"OPEN UNTIL KICKOFF");}}
  function confidence(){weekLabels();var rows=Array.from(S.app.querySelectorAll(".confidence-game-row")).slice(0,6);rows.forEach(function(r,i){var a=r.querySelector(".confidence-matchup-state strong"),b=r.querySelector(".confidence-matchup-state span");if(S.state==="live"){set(a,i?"LIVE":"LIVE · Q3 08:14");set(b,"LOCKED · IN PROGRESS");}else if(S.state==="final-win"||S.state==="final-loss"){set(a,"FINAL");set(b,S.state==="final-win"?"CORRECT":"WRONG");}else{set(a,S.state==="preview"?"SCHEDULED":"UPCOMING");set(b,S.state==="locked"?"LOCKED":S.state==="selected"?"SAVED · Locks at kickoff":"OPEN · Locks at kickoff");}});if(rows[0])stamp(rows[0],LABELS[S.state]||S.state,S.state==="final-loss"?"danger":"info");}
  function fantasy(){weekLabels();var slots=Array.from(S.app.querySelectorAll(".tf-slot")).slice(0,8);slots.forEach(function(s,i){var st=s.querySelector(".tf-slot-status-word"),pt=s.querySelector(".tf-slot-points-r3");if(S.state==="incomplete"&&i<3)set(st,"OPEN");if(S.state==="locked")set(st,"LOCKED");if(S.state==="live"){set(st,"LIVE");if(pt)pt.textContent=(i%2?"8.7":"12.4")+" pts";}if(S.state==="final-win"||S.state==="final-loss"){set(st,"FINAL");if(pt)pt.textContent=(S.state==="final-win"?(14+i*.7):(6+i*.4)).toFixed(1)+" pts";}});var c=S.app.querySelector(".tf-game-day-card,.sports-team-fantasy");if(c)stamp(c,LABELS[S.state]||S.state,S.state==="final-loss"?"danger":"info");}
  function koth(){weekLabels();var b=S.app.querySelector(".sports-default-koth-status,.koth-final-status"),st=b&&b.querySelector("strong"),label="SAFE",count=0;if(S.state==="warning"){label="WARNING ZONE";count=1;}if(S.state==="strike"){label="STRIKE RECEIVED";count=2;}if(S.state==="eliminated"){label="FINAL-ELIMINATED";count=3;}if(S.state==="champion")label="LAST MAN STANDING";if(S.state==="preview")label="WEEK PREVIEW";set(st,label);Array.from(S.app.querySelectorAll(".sports-default-koth-strikes i,.koth-final-mini-strikes i")).slice(0,3).forEach(function(n,i){n.classList.toggle("is-filled",i<count);});var p=S.app.querySelector(".koth-final-player,.koth-final-standing");if(p)stamp(p,label,S.state==="eliminated"?"danger":"info");}
  function wager(){weekLabels();var c=S.app.querySelector(".betting-category-card,.betting-category,.sports-wager-card,.betting-game-card,[data-category-id],.betting-page");if(!c)return;stamp(c,LABELS[S.state]||S.state,S.state==="won"?"success":S.state==="lost"?"danger":"info");if(S.state==="live"||["won","lost","push"].indexOf(S.state)!==-1)score(c,S.state==="live"?"LIVE · Q4 04:12":"FINAL · "+S.state.toUpperCase(),"BUF 27","DET 24");}
  function apply(){if(!S.app)return;restore();if(S.state==="real"){launcher();return;}S.app.inert=true;document.body.classList.add("pattc-testlab-simulating");banner();if(S.type==="survivor")survivor();if(S.type==="confidence")confidence();if(S.type==="team-fantasy")fantasy();if(S.type==="koth")koth();if(S.type==="wager")wager();launcher();}
  function launcher(){var b=document.getElementById("pattcSportsTestLabButton");if(b)b.innerHTML="<strong>TEST LAB</strong><span>"+esc(S.state==="real"?"REAL DATA":(LABELS[S.state]||S.state))+"</span>";}
  function panel(){var o=(STATES[S.type]||[]).map(function(v){return'<option value="'+v+'" '+(v===S.state?"selected":"")+'>'+esc(LABELS[v]||v)+'</option>';}).join("");return'<section id="pattcSportsTestLabPanel" class="pattc-testlab-panel"><div class="pattc-testlab-head"><strong>FOOTBALL TEST LAB</strong><button onclick="pattcSportsTestLabClose()">×</button></div><div class="pattc-testlab-body"><label><span>Game state</span><select onchange="pattcSportsTestLabSetState(this.value)">'+o+'</select></label><label><span>Week</span><div class="pattc-testlab-week-row"><button onclick="pattcSportsTestLabBumpWeek(-1)">‹</button><input type="number" min="1" max="18" value="'+S.week+'" onchange="pattcSportsTestLabSetWeek(this.value)"><button onclick="pattcSportsTestLabBumpWeek(1)">›</button></div></label><button class="pattc-testlab-reset" onclick="pattcSportsTestLabReset()">RESTORE REAL DATA</button></div></section>';}
  function open(){close();document.body.insertAdjacentHTML("beforeend",panel());S.panel=true;}
  function close(){var n=document.getElementById("pattcSportsTestLabPanel");if(n)n.remove();S.panel=false;}
  function mount(page,app){teardown();if(!admin()||!app)return;var t=type(page,app);if(!t)return;S.page=page;S.type=t;S.gameId=gid();S.app=app;S.baseline=app.innerHTML;load();document.body.insertAdjacentHTML("beforeend",'<button id="pattcSportsTestLabButton" class="pattc-testlab-launcher" onclick="pattcSportsTestLabOpen()"><strong>TEST LAB</strong><span>REAL DATA</span></button>');launcher();if(S.state!=="real")apply();}
  function teardown(){close();var b=document.getElementById("pattcSportsTestLabButton");if(b)b.remove();document.body.classList.remove("pattc-testlab-simulating");if(S.app)S.app.inert=false;}
  function before(page,app){if(S.app===app&&S.baseline){app.inert=false;app.innerHTML=S.baseline;}teardown();S={page:"",type:"",gameId:"",app:null,baseline:"",state:"real",week:1,panel:false};}
  root.pattcSportsTestLabMount=mount;root.pattcSportsTestLabBeforeNavigate=before;root.pattcSportsTestLabOpen=open;root.pattcSportsTestLabClose=close;
  root.pattcSportsTestLabSetState=function(v){S.state=txt(v||"real");save();apply();if(S.panel)open();};
  root.pattcSportsTestLabSetWeek=function(v){S.week=Math.max(1,Math.min(18,Number(v||1)||1));save();apply();if(S.panel)open();};
  root.pattcSportsTestLabBumpWeek=function(d){S.week=Math.max(1,Math.min(18,S.week+Number(d||0)));save();apply();if(S.panel)open();};
  root.pattcSportsTestLabReset=function(){S.state="real";S.week=currentWeek();save();close();if(typeof navigate==="function"&&S.page)navigate(S.page,{forceRefresh:true,suppressLoader:true,skipHistoryWrite:true,skipUnsavedCheck:true});else{restore();launcher();}};
})(window);
